### ISSUE TITLE
Is it possible to configure iceTransportPolicy?

### ISSUE THREAD

**Issue by 0tho** [geckosio/geckos.io#1]
I need to force the usage of the TURN server, and by looking around I found [this](https://stackoverflow.com/questions/27224008/webrtc-force-peers-to-use-turn-server) and would like to know if it is possible with geckos.

**Comment by yandeu** [comment]
I have just added support for `iceTransportPolicy` in **@geckos.io/server@1.1.1**.

Based on [this comment](https://stackoverflow.com/a/28849022), it should work by setting it to `relay`.

You can use it like this
```js
// server.js
const io = geckos({
  iceServers: YOUR_TURN_SERVER,
  iceTransportPolicy: 'relay'
})
```
Hope this works :)

**Comment by 0tho** [comment]
Will test it later today and report back

**Comment by yandeu** [comment]
I made few tests. 

It looks like `relay` does not work on the server. Only when I add the `iceServers` to the client and server and add `iceTransportPolicy: 'relay'` to the client, it works.

I will add the `iceServers` and `iceTransportPolicy` options to the client in the next version.

It will probably be done at the end of the week.

**Comment by yandeu** [comment]
I have added it. Please update to the latest versions.

You can use the [simple chat app](https://github.com/geckosio/simple-chat-app-example) to test it. Just add the the iceServers to both, client and server, and add `iceTransportPolicy: 'relay'` to the client.

For me, it did not work on localhost, but once I put it on the server it worked. The firefox webrtc debug page shows a **relay** connection for the Local Candidate and a **srflx** for the Remote Candidate. 

I used [twilio's network traversal service](https://www.twilio.com/stun-turn) to test it.

I hope this is what you are looking for :)

**Comment by yandeu** [comment]
@0tho has this issue been resolved for you?
