### ISSUE TITLE
POST request /.wrtc/v2/connections/id/close hangs

### ISSUE THREAD

**Issue by dadon** [geckosio/geckos.io#100]
If you call channel.close() on the client, the request will hang in a pending state forever.

I'm not sure if it affects something, but when testing a case with constant reconnects - after a certain number of reconnects, the connection stops being established (/.wrtc/v2/connections also starts to hang). 
If I don't call channel.close(), connections will be established until they reach the connection limit in the browser :)

**Comment by sebastianfast** [comment]
I also noticed a behavior similar to yours.

I'm running the server with `nodemon`, after a random (mostly large) number of `nodemon` restarts, the client will not connect anymore. I'm running the server within a Docker container, so after a container restart this problem is fixed most of the times. At other times the client will not connect and I do not understand why. Maybe it is due to the connection limit of the browser,  because I don't explicitly call `channel.close()` on the client.

**Comment by yandeu** [comment]
The wrtc implementation of geckos (`node-datachannel`) got patches 4 times since the last dev versuon of geckos v2.

I will update all dependencies this weekend. Hopefully this resolves some issues.

> If you call channel.close() on the client, the request will hang in a pending state forever.

I will look into it.

**Comment by dadon** [comment]
>At other times the client will not connect and I do not understand why.

It happens to me from time to time too, I couldn't figure out the reason either. So far I've solved it with a hack - if the client can't connect for 5 seconds, the client tries to connect again

**Comment by dadon** [comment]
> The wrtc implementation of geckos (`node-datachannel`) got patches 4 times since the last dev versuon of geckos v2.
> 

How difficult is it to do? We really need it to work next week ¯\_(ツ)_/¯  

dev3 version sometimes crashes due to memory leaks on the server. 
Is it possible that these patches will fix the situation?

**Comment by yandeu** [comment]
I have just published [2.0.0-dev.4](https://www.npmjs.com/package/@geckos.io/server/v/2.0.0-dev.4).
Hopefully, this solves your issues.

**Comment by dadon** [comment]
Awesome, thank you so much 👍
We're already testing...

**Comment by dadon** [comment]
This issue with close is solved, thank you!

I have another issue (or question) - how to proper organise a reconnection process, I will create another issue for this.

**Comment by yandeu** [comment]
> I will create another issue for this

Yes please.

I believe there already is/was an issue or question about this. Maybe search for it.
