### ISSUE TITLE
geckos server https support

### ISSUE THREAD

**Issue by lancety** [geckosio/geckos.io#103]
hi, I am trying to make the server to use https. 

From the "servers" section in ready me, seems I can use https.createServer() with key/pem data. But the borwser still return same error.  Do we have a sample about how to make https server already? Thanks for help.

https://192.168.1.138:9208

![image](https://user-images.githubusercontent.com/5547558/117765643-a7ba8700-b271-11eb-989f-36ef0742e2ee.png)

`

        const httpsServer = https.createServer(serverKey);
        this._geckosServer = geckos({
            authorization: async (auth: string, request: http.IncomingMessage) => {
                try {
                    const authObj: iGSNetworkingAuth = a2json(auth);

                    console.log("### authObj", authObj.playToken);
                    return {
                        creatorToken: authObj.creatorToken,
                        playToken: authObj.playToken,
                        user: rsaDecryption(authObj.playToken, this._playTokenDecodeKey),
                    } as iServerClientUserData;
                } catch (err) {
                    console.error("authorization - no provided")
                    return {};
                }
            },
            cors: {
                // @ts-ignore
                origin: function(req) {
                    const nodeEnv = getNodeEnv();
                    const origin = req.headers.origin;
                    if (nodeEnv.isLocalhost) {
                        return origin;
                    } else {
                        return nodeEnv.hostname;
                    }
                },
                allowAuthorization: true
            },
        });
        this._geckosServer.addServer(httpsServer);
        this._geckosServer.onConnection(channel => {
            const newClient: SC = new GSCNetworking({
                clientChannel: channel,
            }) as SC;
            this._onChannelConnect(newClient.userData.clientId, newClient);
        })
        this._geckosServer.listen(9208);
`

**Comment by yandeu** [comment]
This should help:
https://github.com/geckosio/express-https-test

**Comment by lancety** [comment]
hi @yandeu , I noticed there were 2 issues in my previous version of code
1. I should use httspServer.listen(9208)   not geckos server this._geckosServer.listen(9208)
2. the "serverKey" which I put into https.createServer call have "key" and "pem" prop which should be "key" and "cert" props.  

now it is working~  thanks for sharing the demo 👍

**Comment by yandeu** [comment]
You're welcome 🙂
