### ISSUE TITLE
authorization return false and response content length is 0 with 401 code, but client side err expecting json response

### ISSUE THREAD

**Issue by lancety** [geckosio/geckos.io#104]
I am testing my "authorization" logic to return false when user not signed in, the geckos client.onConnect(err=>{}) have a internal error expecting the response is json, and the err param of callback actually is the internal error description "unexpected end of JSON input". instead of a response object with error code 401

the geckos version is 2.0.0-dev.3

**Comment by yandeu** [comment]
I guess this (https://github.com/geckosio/geckos.io/commit/3db8c0c074121652a4d93bfe1b5d1c2470dee695) is what you are looking for?

**Comment by lancety** [comment]
thanks for the quick fix @yandeu .  Tested it works well
