### ISSUE TITLE
Compile error after upgrading to 2.0.0 using TypeScript

### ISSUE THREAD

**Issue by T-Grave** [geckosio/geckos.io#114]
**Describe the bug**
I get the following error after building the project with the new 2.0.0 version.

```
[ERROR] 11:38:21 Error: Must use import to load ES Module: /Users/robin/Projects/games/dogfight-online/node_modules/@geckos.io/server/lib/index.js
require() of ES modules is not supported.
require() of /Users/robin/Projects/games/dogfight-online/node_modules/@geckos.io/server/lib/index.js from /Users/robin/Projects/games/dogfight-online/server/src/index.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/robin/Projects/games/dogfight-online/node_modules/@geckos.io/server/package.json.
```

I'm importing as follows:
```
import geckos from "@geckos.io/server";
```

I use `ts-node-dev` to compile my project as I'm in a TypeScript environment.

**Comment by T-Grave** [comment]
After some more research it turns out this is not an issue of this library, but rather `ts-node-dev` and `ts-node` limitation with ESM modules. I suspect you changed to an ESM module instead of CommonJS module with the introduction of 2.0.0

For anyone else having this issue; https://github.com/wclr/ts-node-dev/issues/265

It basically means you cannot use `ts-node-dev`.

This does work, but also requires you to add `.js` to all non third party import statements. (and ofcourse does not rerun on change)
```
node --loader ts-node/esm src/index.ts
```

**Comment by yandeu** [comment]
Has this been resolved?

Or do you want to share your repo?

**Comment by T-Grave** [comment]
Unfortunately it was not, for a second I thought it was, so my bad for closing / re-opening :)

I've updated my last comment with the findings up until now.

I'm unable to share my current repo, but if you want I could look into setting up a more barebones version without licensed assets which would represent the problem.

**Comment by yandeu** [comment]
See https://github.com/T-Grave/geckos-esm-issue/pull/1

**Comment by amjadsh97** [comment]
this is a big issue!!

**Comment by yandeu** [comment]
> this is a big issue!!

Why? It is working fine. You just have to learn how to use ECMAScript modules in Node.js.

**Comment by amjadsh97** [comment]
> > this is a big issue!!
> 
> Why? It is working fine. You just have to learn how to use ECMAScript modules in Node.js.

great, could you tell me why when I run npm start the module change from commJS to esnext and the server turned off(i used nodemon)!!

**Comment by yandeu** [comment]
Are you running [this](https://github.com/geckosio/geckos-esm-issue)?  
Just do `npm i; tsc; npm start`.

---

> the module change from commJS to esnext

geckos.io does provide any CommonJS code anymore. But you can still run it in a CommonJS codebase using Dynamic Imports.  
Read: [2020-05-28-esm-for-nodejs.md](https://github.com/yandeu/yandeu/blob/main/posts/2020-05-28-esm-for-nodejs.md)

**Comment by Enijar** [comment]
Would it be possible to ship two versions: an ESM one and a CJS one to have something like the below?

```ts
import geckos from "@geckos.io/server/cjs"; // Opt-in to CJS
import geckos from "@geckos.io/server"; // Default EJS
```

I think this would be useful for devs who are using a build system that outputs CJS.

**Comment by ghyath5** [comment]
Any updates here ??

**Comment by yandeu** [comment]
It sill uses ESM. This will probably not change.

**Comment by yandeu** [comment]
But still, this is NOT an issue. You can import and use geckos.io in any cjs project.

Here an example:
[https://github.com/geckosio/geckos-v2-cjs-example](https://github.com/geckosio/geckos-v2-cjs-example)

**Comment by yandeu** [comment]
> Would it be possible to ship two versions: an ESM one and a CJS one to have something like the below?
> 
> ```ts
> import geckos from "@geckos.io/server/cjs"; // Opt-in to CJS
> import geckos from "@geckos.io/server"; // Default ESM
> ```
> 
> I think this would be useful for devs who are using a build system that outputs CJS.

I am just working on an implementation like this. See https://github.com/geckosio/geckos.io/commits/cjs

**Comment by yandeu** [comment]
> Keep up the great work.

Thanks! I will.

Yes, it depends where your users live and what connection they have.  
For a Starlink user, for example, a WebSocket Action Shooter will not be very enjoyable. But for most landlines, WebSockets is not drawback.
