### ISSUE TITLE
Connection Error in Deployment with Heroku

### ISSUE THREAD

**Issue by DolphinIQ** [geckosio/geckos.io#13]
Hi! I'm very excited to use geckos for my game :) 
Unfortunately Im running into an error after deploying to my test server on Heroku. Basically it waits around 2-3 minutes and then logs these errors:

![image](https://user-images.githubusercontent.com/34486337/73598876-a57d5f00-453d-11ea-8038-c5736b4562ff.png)

It works completely fine locally. I use both client and server geckos versions `^1.3.0-alpha.0`, with node `v12.9.1` Server file is imported with `require`, and the client uses a minified script added to the head tag.

Relevant Server Code:
```
const geckos = require('@geckos.io/server').default;
const { iceServers } = require('@geckos.io/server');
const express = require('express'),
const app = express();

let io = geckos({
     iceServers: process.env.NODE_ENV === 'production' ? iceServers : [] 
});

// Tried also with port 9208
let server = app.listen( process.env.PORT || 3000, () => {
   console.log("Server started on port 3000...");
});
io.addServer( server );
```

Client: 
```
// Inside <head>
<script src="js/geckos/client.min.js"></script>

// Inside App
const channel = geckos({
      port: 3000,
});
// Also tried passing the hosted adress into url option, but result was the same
```

Any idea what might be the cause?

P.S. not sure if its relevant, but the website is at `mydomain.herokuapp.com`, while the game (alongside with the geckos client) runs on `mydomain.herokuapp.com/play`

**Comment by yandeu** [comment]
It is not possible to run geckos.io on heroku. Heroku does not allow to forward the required ports. 
See the [deployment section](https://github.com/geckosio/geckos.io#deployment) of geckos.io.

**Comment by DolphinIQ** [comment]
Thank you for such a quick response. Im not very knowledgeable on the topic. Are there any resources you could recommend for educational purposes? Or maybe just recommend which server providers work with geckos?

**Comment by yandeu** [comment]
I use [ec2](https://aws.amazon.com/ec2/), (I guess [lightsail](https://aws.amazon.com/lightsail/) does also work well).

A simpler solution would be [DigitalOcean](https://www.digitalocean.com/).

Hope this helps :)
