### ISSUE TITLE
List Number of Clients in a Room

### ISSUE THREAD

**Issue by OADesigns** [geckosio/geckos.io#136]
I can't seem to find a way to get the a list of the clients connected to a room, I think I am misunderstanding something or perhaps it's not a feature?
 When I try to call just the room using the id in this fashion:
 io.room(channel.roomId)) or channel.room(roomId)
the object I get back only has the emit function in it, is there no list of clients or is it somewhere else?
Should I create my own object and add each client when they join the room or does this already exist?

**Comment by yandeu** [comment]
I guess you could use the connectionsManager, find all channels and their roomId.

```ts
io.connectionsManager.getConnections()
```

**Comment by OADesigns** [comment]
Yes thank you that helped. I was able to create a function that returned an array with the client ids in a specific room with this:
function getRooms(roomToFind/**string**/, roomLimit /**optional int limit**/) {
    var map= io.connectionsManager.getConnections()
    var roomList = []
    for (var x of map.entries()) {
        if (x[1].channel.roomId === roomToFind) {
           roomList.push(x[1].channel.id)
            if(typeof roomLimit !== 'undefined' && roomList.length === roomLimit){
                break
            }
        }
    }
    return roomList
}
It seems to work. You can close this issue if you'd like.

**Comment by yandeu** [comment]
:+1:
