### ISSUE TITLE
Uncaught exception in connections manager on connection breakup

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [geckosio/geckos.io#150]
When the connection to the Geckos server dies for any reason, the `onDisconnect` event triggers correctly. However, the console still shows an uncaught exception. Is there any promise I can catch to prevent this?

What I tried without success:
```javascript
const connectToGeckos = async () => {
  const channel = geckos({ port: 3000, authorization: "barbaz" });

  await channel.onConnect((connectError) => {
    if (connectError) {
      console.error("Error while connecting to Geckos", connectError);
      return;
    }

    channel.onDisconnect((disconnectReason) => {
      console.log("Disconnected", disconnectReason);
    });
  });
  return channel;
};

const main = async () => {
  try {
    const geckosChannel = await connectToGeckos();
  } catch (e) {
    console.log("promise caught")
  }
}

main();

```
When I kill the Geckos server, I see a stacktrace and then the `Disconnected undefined` log. 

Looks like the uncaught errors come from this line: https://github.com/geckosio/geckos.io/blob/61a801f504da04315d0985bbe8ef66f27afa0eea/packages/client/src/wrtc/connectionsManager.ts#L150

Would it help if we wrapped the body of `setTimeout` in a promise?

<img width="889" alt="Screen Shot 2021-12-30 at 4 50 36 pm" src="https://user-images.githubusercontent.com/278624/147725422-f1c5f1c2-b25d-4e28-baf8-7a0c7c043ed3.png">

```
Uncaught (in promise) TypeError: Failed to fetch
    at ConnectionsManagerClient.fetchAdditionalCandidates (connectionsManager.js:31)
    at connectionsManager.js:117
  | fetchAdditionalCandidates | @ | connectionsManager.js:31
  | (anonymous) | @ | connectionsManager.js:117
  | await in (anonymous) (async) |   |  
  | (anonymous) | @ | connectionsManager.js:117
  | setTimeout (async) |   |  
  | (anonymous) | @ | connectionsManager.js:116
  | connect | @ | connectionsManager.js:115
  | await in connect (async) |   |  
  | connect | @ | peerConnection.js:7
  | onConnect | @ | channel.js:86
  | connectToGeckos | @ | app.ts:34
  | main | @ | app.ts:66
  | 7146 | @ | app.ts:75
  (webpack entries omitted)
```

**Comment by yandeu** [comment]
Is this the same as https://github.com/geckosio/geckos.io/discussions/149?

Is the error only client-side?

I guess appending a `.catch(() => {})` to`fetchAdditionalCandidates()` would do the trick?

**Comment by hubertgrzeskowiak** [comment]
> Is this the same as #149?
> Is the error only client-side?

That issue seems to be about server. My report is only concerning an error log on the client that can not be muted.

> I guess appending a `.catch(() => {})` to`fetchAdditionalCandidates()` would do the trick?

I reckon it would! Is it safe to add an empty function, or should we make it emit some events so that the client can react to that?

**Comment by yandeu** [comment]
I guess an event would be better.

**Comment by yandeu** [comment]
I have added `.catch(() => {})` in https://github.com/geckosio/geckos.io/commit/92391e690e81477c9215a747afe0f0e2dd1370f1.
