### ISSUE TITLE
No way to broadcast raw message to all sockets

### ISSUE THREAD

**Issue by andrewmunro** [geckosio/geckos.io#17]
I'm trying to use msgpack to compress my messages.

I can send a raw message directly to a socket with `channel.raw.emit(data)` but I can't seem to broadcast messages to all connections.

There only seems to be a `server.emit` method available.

**Comment by yandeu** [comment]
In the next release you will be able to use all of these functions.
```js
// emit a raw message
channel.raw.emit(rawMessage)

// emit a raw message to all users in the same room
channel.raw.room.emit(rawMessage)

// broadcast a raw message
channel.raw.broadcast.emit(rawMessage)
```
