### ISSUE TITLE
No way to disconnect client

### ISSUE THREAD

**Issue by lucas-jones** [geckosio/geckos.io#18]
I couldn't find a way to disconnect a client/socket?

Maybe I've missed somthing

**Comment by yandeu** [comment]
Only the server can close the connection for now. Just send a close request (emit a message) to the server which then closes the connection with `channel.close()`.

**Comment by lucas-jones** [comment]
Alright cheers! Awesome library 👍

**Comment by yandeu** [comment]
In the next release you will be able to call `channel.close()` on the client.
