### ISSUE TITLE
Couldn't install package on m1 mac

### ISSUE THREAD

**Issue by kayden1940** [geckosio/geckos.io#187]
info TOOL Using Unix Makefiles generator.
ERR! OMG CMake executable is not found. Please use your system's package manager to install it, or you can get installers from there: http://cmake.org/.
prebuild ERR! build Error: Failed to build cmake with exit code 1

with both yarn and npm

**Comment by DarePhoenix** [comment]
What nodejs version are you using ? 

For now it's not working with nodejs 17 because node-datachannel don't have prebuilt binnaries for it

**Comment by dustinlacewell** [comment]
I've tried 16 and 17 and neither work.

**Comment by dadon** [comment]
This worked for me:

```
brew install cmake
brew install openssl
brew link --force openssl
```

**Comment by nikitaosyak** [comment]
I was able to install dependency by updating to latest node and npm, and using install instructions from @dadon's answer.

thanks.

**Comment by watch-janick** [comment]
I'm on a M1 Max using MacOS 12.5 and I'm getting this error when trying to build it with Node v18.7.0:

<img width="1166" alt="Screenshot 2022-08-22 at 16 54 56" src="https://user-images.githubusercontent.com/11473142/185954951-df2b26e3-0aa1-4e8f-ab6a-0ee4075e2707.png">

Any idea?

**Comment by yandeu** [comment]
Can you please try v2.2.3?
_Just release a minute ago_

**Comment by watch-janick** [comment]
I realised I had `node-datachannel` in my dependencies which wasn't needed and I think that was the actual issue.

It's working now!

**Comment by yandeu** [comment]
Glad to hear :)
