### ISSUE TITLE
Can't fix vulnerabilities

### ISSUE THREAD

**Issue by DarePhoenix** [geckosio/geckos.io#195]
Hey, when I'm installing geckos.io, it give me 2 vulnerabilities (high and critical) :

![image](https://user-images.githubusercontent.com/86203108/164411023-c39a3e73-ef67-43f9-aeb2-4a5adb9d9641.png)

So i'm trying to fix, it but it's not working : 

![image](https://user-images.githubusercontent.com/86203108/164411127-e6927452-1578-4e02-b8ec-7788b02f2fe6.png)

So any idea how can I fix it ?

**Comment by yandeu** [comment]
These are inside node-datachennel. Probably only dev dependencies. Geckos.io does not use the latest node-datachennel yet. Maybe upgrading to the latest version and releasing a new geckos version will fix it.

**Comment by DarePhoenix** [comment]
> These are inside node-datachennel. Probably only dev dependencies. Geckos.io does not use the latest node-datachennel yet. Maybe upgrading to the latest version and releasing a new geckos version will fix it.

So can you update it ? It's actually using node-datachannel 2.0 when I'm downloading geckos.io

**Comment by yandeu** [comment]
Done. Please try it.

**Comment by yandeu** [comment]
> Also, if you get time, before updating, can you check a little list of new freatures that I made in [discussions](https://github.com/geckosio/geckos.io/discussions/192)

I'm sorry. I don't have much time these days. But feel free to make a PR.

**Comment by DarePhoenix** [comment]
Ok thanks, ill try if I get time
