### ISSUE TITLE
Cannot reconnect after closing

### ISSUE THREAD

**Issue by DarePhoenix** [geckosio/geckos.io#196]
Hey, I'm trying to close my socket, and then connect again to the same server (but need it to works for a different one too) like that, but it's not working (I don't recieve "gameVersion").

Client ;
```js
let socket = geckos({ url: "http://localhost", port: 15000, label: "wild.io" });

socket.onConnect(error => {
	if (error) console.error(error.message)

	setTimeout(() => {
		socket.close();

		setTimeout(() => {
			socket = geckos({ url: "http://localhost", port: 15000, label: "wild.io" });

			socket.on("gameVersion", function() {
				console.log("works")
			})
		}, 2500);
	}, 1000);
})
```

Server :

```js
const server = geckos({
	label: "wild.io",
	cors: { origin: "*", allowAuthorization: true }
});

const sockets = server;

server.listen(15000);

server.onConnection(function(socket) {
      socket.emit("gameVersion", 1.0);
});
```

I get this error on the console after closing the socket :

![image](https://user-images.githubusercontent.com/86203108/165319420-368d77ea-cfbc-4f25-bfd5-56a9621291a2.png)

Any suggestion about how can I close and then create a new connection ?

**Comment by DarePhoenix** [comment]
I think I made a misstake, it works now. Also can you fix closing the channel spam the messages error that I put above ?

**Comment by yandeu** [comment]
> Also can you fix closing the channel spam the messages error that I put above ?

Fixed in https://github.com/geckosio/geckos.io/commit/e9af90bfe6575609f44c1e140233e0db977ed410
