### ISSUE TITLE
Error connection aborted

### ISSUE THREAD

**Issue by DarePhoenix** [geckosio/geckos.io#208]
Hello, when I load my page, the client connect to 4 differents servers, do some checks, then disconnect from all the servers, and connect to a new server.

But some peoples actually facing this issue :

![image](https://user-images.githubusercontent.com/86203108/171436302-43bd9ddb-5802-4b26-a422-59a96e62161f.png)

I don't know when it's happening, because it works perfectly fine for me, but don't work randomly for some peoples (if it don't work one time, it never work).

I'm actually using this server code :

```js
import { createSecureServer } from "http2"

const options = {
    key: readFileSync(`path...`),
    cert: readFileSync(`path...`),
}

const HTTPServer = createSecureServer(options);

const server = geckos({
  authorization: async function (auth, request) {
      return {
          ip: request.socket.remoteAddress.replace("::ffff:", ""),
          type: auth,
      }
  },
  label: "wild.io",
  cors: { origin: "*", allowAuthorization: true }
});

server.addServer(HTTPServer)

HTTPServer.listen(8080, function() {
  console.log("Server successfully started !");
});
```
I'm using http2, but some peoples still get the same error, even when using express as on the https exemple

Any idea about how can I fix it ?

**Comment by yandeu** [comment]
Not sure.

But I highly recommend not using geckos just for simple checks. Please use normal http requests instead if possible.

**Comment by DarePhoenix** [comment]
> Not sure.
> 
> But I highly recommend not using geckos just for simple checks. Please use normal http requests instead if possible.

I could do http requests checks for player number check, but it's too checking the latency. I'm don't think that an http request will giving real results for this.

**Comment by yandeu** [comment]
Ooh yes. I see.

**Comment by yandeu** [comment]
Is there a way to reproduce the error locally?

**Comment by DarePhoenix** [comment]
Uhm I don't know, it never happen to me, and works for most of peoples. A minority of persons are getting this error (peoples are located all arround the world).
