### ISSUE TITLE
has been blocked by CORS policy

### ISSUE THREAD

**Issue by vitalspace** [geckosio/geckos.io#209]
First of all I have been trying to solve this on my own but I have obviously not been able to.

Well I have the following:

Frontend error:

![Screenshot_1](https://user-images.githubusercontent.com/29004070/173176717-9fdf239e-8d30-4942-9d5a-709473b0e6c1.png)

Backend
![Screenshot_2](https://user-images.githubusercontent.com/29004070/173176521-0d4f3f2a-ed09-41a4-a086-041737b889ad.png)

```
import cors from "cors";
import http from "http";
import express from "express";
import path from 'path'

const port = 8080
const app = express();
const server = http.createServer(app);

app.use(cors());
app.use(express.json())
app.use(express.urlencoded({ extended: true }));

const main = async () => {
  // import geckos as ESM
  const { geckos } = await import('@geckos.io/server')
  const io = geckos({
      cors: { 
          origin: 'https://mywebsite.zyx',
          allowAuthorization: true,
        }
    })

  io.addServer(server)
  io.onConnection(channel => {
    console.log("New connection", channel.id)
    channel.onDisconnect(() => {
      console.log(`${channel.id} got disconnected`)
    })
   channel.emit(   "hello", "hello frontend");
    } catch (error) {
      console.log(error)
    }
    })
  })
  server.listen(port, () => {
    console.log(`Example app listening at http://localhost:${port}`)
  })
}
main()

```

Nginx

![Screenshot_3](https://user-images.githubusercontent.com/29004070/173176704-9f853f6b-4529-4286-93e9-8e15195fbd1d.png)

**Comment by vitalspace** [comment]
Well this is what I get on the frontend when it tries to connect to geeckos. I already tried a thousand ways and I can't find the answer, does anyone know how to solve this? by the way i am using geckos 2.2.0. I don't put screenshots of the frontend because I know this has nothing to do with the frontend.

**Comment by yandeu** [comment]
Does `origin: '*'` work?

**Comment by yandeu** [comment]
`origin: 'https://mywebsite.zyx'` is not the same as ` origin: 'https://www.mywebsite.zyx'`.

Try:
`origin: 'https://mywebsite.zyx https://www.mywebsite.zyx'`

**Comment by vitalspace** [comment]
> Does `origin: '*'` work?

when trying this way I get:

![Screenshot_1](https://user-images.githubusercontent.com/29004070/173195793-9b89a0f6-e806-4d58-aca1-5458a879c3f4.png)

Backend 

![Screenshot_2](https://user-images.githubusercontent.com/29004070/173195805-6e292521-9578-45c3-bfeb-5860918f9fd0.png)




> `origin: 'https://mywebsite.zyx'` is not the same as ` origin: 'https://www.mywebsite.zyx'`.
> 
> Try: `origin: 'https://mywebsite.zyx https://www.mywebsite.zyx'`

I also tried this way and received the same as at the beginning.

**Comment by yandeu** [comment]
Well, now you have a strange `:8080` in the url.

**Comment by vitalspace** [comment]
Sorry, I was trying to change ports, but the answer is the same.
![Screenshot_3](https://user-images.githubusercontent.com/29004070/173196310-68a9ecf1-53b7-48c9-96f0-4eb8e91551f0.png)

**Comment by yandeu** [comment]
Ok. But a 404 error has nothing to do with CORS.
Now the issue must be something else.

**Comment by yandeu** [comment]
I think I know what the issue is.
Can you route geckos to `https://yourapp.com/.wrtc/v2`? (Without `/mysocket`)

**Comment by vitalspace** [comment]
nope 

> I think I know what the issue is. Can you route geckos to `https://yourapp.com/.wrtc/v2`? (Without `/mysocket`)

![Screenshot_4](https://user-images.githubusercontent.com/29004070/173196926-e568d74f-8d61-4695-a693-5fe2fe7c9497.png)

**Comment by yandeu** [comment]
Have you also changes the location in nginx?

**Comment by vitalspace** [comment]
nope 

![Screenshot_5](https://user-images.githubusercontent.com/29004070/173196958-d173f1e8-1b57-4061-abf3-0f92f805a6b6.png)

**Comment by yandeu** [comment]
Have you also changes the location in nginx?

**Comment by vitalspace** [comment]
yeah that's the error, it was solved with this:

Nginx 
![Screenshot_6](https://user-images.githubusercontent.com/29004070/173197374-62e28ba8-3d17-4668-8b5e-2b2ca4c79876.png)

Frontend

![Screenshot_8](https://user-images.githubusercontent.com/29004070/173197399-a07cf194-0896-4ae1-9ed7-65938cf07817.png)

Backend

![Screenshot_9](https://user-images.githubusercontent.com/29004070/173197461-17fde59c-4465-4ac1-a840-71b71773e14a.png)
![Screenshot_10](https://user-images.githubusercontent.com/29004070/173197462-e10a57d4-a498-4943-ad46-c68826716e13.png)

**Comment by yandeu** [comment]
Cool. I will improve to code (in this block below) to allow subpaths like your `/mysocket`.

**Comment by vitalspace** [comment]
thanks that will help, I was yesterday almost all day trying to solve this. But thanks to your help again it was done.

**Comment by yandeu** [comment]
You're welcome. Fix will be available in the next version.
