### ISSUE TITLE
Connection is never established, never throwing an error, just being stuck (Apple Silicon)

### ISSUE THREAD

**Issue by akirilyuk** [geckosio/geckos.io#215]
**Describe the bug**
Hi, I have an issue running geckos on the M1 Mac. Same code works fine on Windows 10 machines.

Symptoms description: 

I have used the [Simple Chat App Example](https://github.com/geckosio/simple-chat-app-example) to validate that the setup works for me and it does not. Same example works fine for a colleague running on Windows.

Basically, the server is starting fine and I can see the output below:

![Screenshot 2022-07-11 at 16 21 02](https://user-images.githubusercontent.com/45361199/178286300-13bfab6f-acff-4a1a-9925-190c82bc3ae8.png)

However, the page itself gets stuck on the onConnect event:

<img width="1728" alt="Screenshot 2022-07-11 at 16 21 36" src="https://user-images.githubusercontent.com/45361199/178286421-260ca5bf-f6b4-4ccc-b978-bd8d72c424e6.png">

You can see that it has reached out to connections and got a 200 OK:

`POST http://127.0.0.1:3000/.wrtc/v2/connections`
```json
{"userData":{},"id":"9ZIrqrULsvwqdi1SrqiVnRGT","localDescription":{"sdp":"v=0\r\no=rtc 1468134362 0 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic:WMS *\r\na=setup:actpass\r\na=ice-ufrag:3qcO\r\na=ice-pwd:8qtyn71ZnTIT55jUdSPC08\r\na=ice-options:ice2,trickle\r\na=fingerprint:sha-256 AC:F5:AD:AC:85:3A:4D:A4:47:5B:B2:49:C9:B9:B3:70:62:EE:D2:75:CD:30:76:17:45:BB:59:2B:9C:A9:BE:CD\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=mid:0\r\na=sendrecv\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n","type":"offer"}}
```

The client then sends a response and gets a 200 OK
`POST http://127.0.0.1:3000/.wrtc/v2/connections/9ZIrqrULsvwqdi1SrqiVnRGT/remote-description`

```json
{"type":"answer","sdp":"v=0\r\no=- 8307945428496414585 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:oNJb\r\na=ice-pwd:IcL0BKV/56KRaeSppRRC4klb\r\na=ice-options:trickle\r\na=fingerprint:sha-256 41:C0:4D:6E:A7:1E:CD:77:D3:02:05:DD:28:3D:2A:BF:BE:18:7C:28:F6:23:E5:28:BC:E6:8D:F1:E1:CD:03:CB\r\na=setup:active\r\na=mid:0\r\na=sctp-port:5000\r\na=max-message-size:262144\r\n"}
```

However the connection never gets established and I am not seing the "You're connected :)" message from here:
![Screenshot 2022-07-11 at 16 25 14](https://user-images.githubusercontent.com/45361199/178287208-54b592c6-11cd-4dad-86eb-84ccb1ccecdd.png)

In fact, nothing happens, in the server code it seems that the connection is also not working/reaching the server. The only thing being done are calls to `additional-candidates`, so it means it fails to connect to the initial provided server in the SDP right?

What would at least help, is a descriptive error message if the connection could not be established, rather than everything just remaining silent. 

From now it looks like the UDP connections never gets established between my client and server and I am really curious to know how I could fix this and appreciate any help here!

Some more info on my hardware

Mac M1 Pro 
M1 Max
macOS Monterey 12.0.1
Node 16.13.1 but also trief with 18.5.0, same result

**Comment by akirilyuk** [comment]
I found out the reason for the issue:

I have installed `libressl-devel` instead of openssl. Strange thing is, everything could compile without any issues.

After removing `libressl-devel` + installing `openssl` via `brew` it worked.

However you need also to add these env vars, otherwise it cannot find openssl.

```sh
export OPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl@1.1/
export OPENSSL_LIBRARIES="/opt/homebrew/opt/openssl@1.1/lib"
```

**Comment by ryan-cranfill** [comment]
I was having a similar issue (on an M1), and reinstalling using those env vars wasn't helping either. Gave the simple chat app example a try, and it connected no problem. 

I then tried bringing in the latest minified client from [here](https://github.com/geckosio/geckos.io/tree/master/bundles) (2.2.2) and my client connected just fine in my app. 

I downgraded my @geckos.io/client to 2.1.8, and now i can use `import { geckos } from '@geckos.io/client';` to connect to my server (which is running 2.2.2). Unsure why the minified version of 2.2.2 works but the npm version doesn't, but there appears to be something in the latest release that was causing my client connection attempt to silently fail.

**Comment by yandeu** [comment]
I have just update the [simple-chat-app-example](https://github.com/geckosio/simple-chat-app-example) to use the npm version of @geckos.io/client and it worked fine. Can you please test the update example?

**Comment by ryan-cranfill** [comment]
The test example works perfectly for me. I also upgraded the client version to 2.2.2 in my project and it's working as well. Not quite sure what changed... was having issues with Parcel, might have been related to that?

In any case the issues I was having seem to be fully resolved (was also having trouble installing prior to 2.2.2, as I believe was referenced in conversation #218 ). Thanks for a great library!

**Comment by yandeu** [comment]
> was having issues with Parcel, might have been related to that?

I don't know. Maybe. I don't use Parcel.

> Thanks for a great library!

You're welcome:)

**Comment by yandeu** [comment]
@akirilyuk Does this now work for you as well?

**Comment by akirilyuk** [comment]
@yandeu everything works for me after setting up the correct OPENSSL env vars as described above. Before that, I have used `libressl-devel` instead of `openssl@1.1`, thats why it did not work. Funny thing is, that the `node-datachannel` could still be compiled successfully, but just silently did not work.

Now everything works as expected, thank you :)

**Comment by yandeu** [comment]
Glad to hear :)

**Comment by auberryberry** [comment]
I hate to be an issue re-opener, but I'm seeing the same behaviour:
client 2.2.3 - via create-react-app site served via webpack.
server 2.2.3 - served via ngrok + on wsl

Connecting from a windows machine, no worries, all good, works as expected.
Connecting from an m1 mac, nothing, I can see the HTTP requests from the m1 to the server and instrumenting the server I can log the requests, but the connection never gets established beyond that.

I've spent a couple of hours switching node versions back and forth and did the openssl@1.1 env-vars, but no dice.
Node versions tried v18.9.0, v16.11.0
Any helpful hints?

**Comment by yandeu** [comment]
> Connecting from an m1 mac, nothing, I can see the HTTP requests from the m1 to the server and instrumenting the server I can log the requests, but the connection never gets established beyond that.

You are connecting from "M1 mac browser" to the "Windows+wsl server"?

**Comment by auberryberry** [comment]
Correct!
[Client] M1 - 14" Pro  - Chrome 105.0.5195.125 (official build) (arm64) ->
[Server]  Windows -> WSL -> Ubuntu -> Node 18.9.0

**Comment by auberryberry** [comment]
Update: Hang fire on this, I think it's actually something else, will report back

**Comment by auberryberry** [comment]
I think this is because the SDP offer is being sent as 127.0.0.1, with nothing to do with m1 and more to do with me being a WebRTC n00b; I guess ngrok can't solve all problems ;)

**Comment by yandeu** [comment]
> I think this is because the SDP offer is being sent as 127.0.0.1

That was my thought as well.
