### ISSUE TITLE
Cant install on mac (intel)

### ISSUE THREAD

**Issue by ziarmandhost** [geckosio/geckos.io#218]
### I do next:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/30569343/183261826-3779a3af-569b-4e1b-be55-ff1d0b65fa92.png">

**Comment by ziarmandhost** [comment]
`npm ERR! code 2
npm ERR! path /Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel
npm ERR! command failed
npm ERR! command sh /var/folders/jt/wz6wftv17gx65c_8w40nrccm0000gn/T/install-fe6bb758.sh
npm ERR! added 595 packages, removed 1 package, and audited 653 packages in 16s
npm ERR!
npm ERR! 66 packages are looking for funding
npm ERR!   run `npm fund` for details
npm ERR!
npm ERR! 4 high severity vulnerabilities
npm ERR!
npm ERR! To address all issues (including breaking changes), run:
npm ERR!   npm audit fix --force
npm ERR!
npm ERR! Run `npm audit` for details.
npm ERR!
npm ERR! > node-datachannel@0.3.3 _prebuild
npm ERR! > prebuild --backend cmake-js
npm ERR!
npm ERR! [
npm ERR!   '/usr/local/Cellar/node/18.7.0/bin/node',
npm ERR!   '/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel/node_modules/.bin/cmake-js',
npm ERR!   'rebuild',
npm ERR!   '--runtime-version=18.7.0',
npm ERR!   '--arch=x64',
npm ERR!   '--runtime=node'
npm ERR! ]
npm ERR! Not searching for unused variables given on the command line.
npm ERR! -- The C compiler identification is AppleClang 13.0.0.13000027
npm ERR! -- The CXX compiler identification is AppleClang 13.0.0.13000027
npm ERR! -- Detecting C compiler ABI info
npm ERR! -- Detecting C compiler ABI info - done
npm ERR! -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
npm ERR! -- Detecting C compile features
npm ERR! -- Detecting C compile features - done
npm ERR! -- Detecting CXX compiler ABI info
npm ERR! -- Detecting CXX compiler ABI info - done
npm ERR! -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
npm ERR! -- Detecting CXX compile features
npm ERR! -- Detecting CXX compile features - done
npm ERR! -- Configuring incomplete, errors occurred!
npm ERR! See also "/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel/build/CMakeFiles/CMakeOutput.log".
npm ERR! See also "/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel/build/CMakeFiles/CMakeError.log".
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=18.7.0 runtime=node arch=x64 libc= platform=darwin)
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! prebuild info begin Prebuild version 11.0.4
npm ERR! prebuild info build Preparing to prebuild node-datachannel@0.3.3 for node 18.7.0 on darwin-x64 using cmake-js
npm ERR! info TOOL Using Unix Makefiles generator.
npm ERR! info CMD CLEAN
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '-E',
npm ERR! info RUN   'remove_directory',
npm ERR! info RUN   '/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel/build'
npm ERR! info RUN ]
npm ERR! info CMD CONFIGURE
npm ERR! info RUN [
npm ERR! info RUN   'cmake',
npm ERR! info RUN   '/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel',
npm ERR! info RUN   '--no-warn-unused-cli',
npm ERR! info RUN   '-G',
npm ERR! info RUN   'Unix Makefiles',
npm ERR! info RUN   '-DCMAKE_JS_VERSION=6.3.2',
npm ERR! info RUN   '-DCMAKE_BUILD_TYPE=Release',
npm ERR! info RUN   '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel/build/Release',
npm ERR! info RUN   '-DCMAKE_JS_INC=/Users/davidziarmand/.cmake-js/node-x64/v18.7.0/include/node;/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel/node_modules/nan',
npm ERR! info RUN   '-DCMAKE_JS_SRC=',
npm ERR! info RUN   '-DNODE_RUNTIME=node',
npm ERR! info RUN   '-DNODE_RUNTIMEVERSION=18.7.0',
npm ERR! info RUN   '-DNODE_ARCH=x64',
npm ERR! info RUN   '-DCMAKE_OSX_ARCHITECTURES=x86_64',
npm ERR! info RUN   '-DCMAKE_CXX_FLAGS=-D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION',
npm ERR! info RUN   '-DCMAKE_SHARED_LINKER_FLAGS=-undefined dynamic_lookup'
npm ERR! info RUN ]
npm ERR! CMake Error at /usr/local/Cellar/cmake/3.24.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
npm ERR!   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
npm ERR!   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
npm ERR!   OPENSSL_INCLUDE_DIR)
npm ERR! Call Stack (most recent call first):
npm ERR!   /usr/local/Cellar/cmake/3.24.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
npm ERR!   /usr/local/Cellar/cmake/3.24.0/share/cmake/Modules/FindOpenSSL.cmake:599 (find_package_handle_standard_args)
npm ERR!   CMakeLists.txt:26 (find_package)
npm ERR!
npm ERR!
npm ERR! ERR! OMG Process terminated: 1
npm ERR! prebuild ERR! build Error: Failed to build cmake with exit code 1
npm ERR! prebuild ERR! build     at ChildProcess.<anonymous> (/Users/davidziarmand/WebstormProjects/geckos-v2-cjs-example/node_modules/node-datachannel/node_modules/prebuild/cmakebuild.js:32:19)
npm ERR! prebuild ERR! build     at ChildProcess.emit (node:events:513:28)
npm ERR! prebuild ERR! build     at ChildProcess._handle.onexit (node:internal/child_process:291:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidziarmand/.npm/_logs/2022-08-06T18_36_18_273Z-debug-0.log`

**Comment by ziarmandhost** [comment]
@trezy @paullouisageneau @bennlich @emansom how to solve this?

**Comment by ziarmandhost** [comment]
Still cant fix this, I tried:

brew install cmake
brew install openssl
brew link --force openssl

NOT Helped

**Comment by paullouisageneau** [comment]
What happens is that node-datachannel has no prebuilt binaries for node 18 (@murat-dogan could confirm), so it tries to build but it fails to find OpenSSL on your machine, which is a common issue with MacOS:
```
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
npm ERR! system variable OPENSSL_ROOT_DIR
```

You should set `OPENSSL_ROOT_DIR` to the correct path before building, something like:
```
$ export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl\@1.1/1.1.1q
```

**Comment by ziarmandhost** [comment]
No, thats not working for me
[2022-08-06T20_43_49_803Z-debug-0.log](https://github.com/geckosio/geckos.io/files/9275745/2022-08-06T20_43_49_803Z-debug-0.log)


> What happens is that node-datachannel has no prebuilt binaries for node 18 (@murat-dogan could confirm), so it tries to build but it fails to find OpenSSL on your machine, which is a common issue with MacOS:
> 
> ```
> Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
> npm ERR! system variable OPENSSL_ROOT_DIR
> ```
> 
> You should set `OPENSSL_ROOT_DIR` to the correct path before building, something like:
> 
> ```
> $ export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl\@1.1/1.1.1q
> ```

**Comment by yandeu** [comment]
I suggest simply falling back to the latest Node.js LTS version 16.16.0.

**Comment by ziarmandhost** [comment]
> I suggest simply falling back to the latest Node.js LTS version 16.16.0.

yep, thats works for me, thanks

**Comment by ziarmandhost** [comment]
@paullouisageneau @yandeu @trezy @bennlich but please dont write that geckos.io supports node v16 >=, because nodejs 17 and 18 is not supported (my case)

**Comment by murat-dogan** [comment]
Hi 
Actually node-datachannel has v17 support.
This week I can add v18 binaries.
It should not be a problem.

Do you have any comment for v17?

**Comment by ziarmandhost** [comment]
> Hi Actually node-datachannel has v17 support. This week I can add v18 binaries. It should not be a problem.
> 
> Do you have any comment for v17?

no, I just tested it on node v18, thanks for adding v18 binaries!

**Comment by murat-dogan** [comment]
Hi,

I have just released `v0.3.5` with latest `libdatachannel` & node v18 support.
For Mac M1 I need someone for testing.
https://github.com/murat-dogan/node-datachannel/issues/120#issuecomment-1188882137

**Comment by yandeu** [comment]
@murat-dogan Thanks a lot!

`v0.3.5` will be in geckos `>= v2.2.2`.

_Will re-close this issue once it has been tested on Mac M1._

**Comment by yandeu** [comment]
I just published v2.2.2 to npm.

@ziarmandhost Can you test it on M1 with Node.js 18?

**Comment by ziarmandhost** [comment]
> I just published v2.2.2 to npm.
> 
> @ziarmandhost Can you test it on M1 with Node.js 18?

I dont have M1, in title of this issue I mentioned that I have intel, sorry man, I wish I could help with testing, but I dont have m1 mac

**Comment by ziarmandhost** [comment]
I could test later on my intel, if you need

**Comment by yandeu** [comment]
> I dont have M1

Sorry. I misread.

> I could test later on my intel, if you need

Guess this would help as well :)

**Comment by ziarmandhost** [comment]
> > I dont have M1
> 
> Sorry. I misread.
> 
> > I could test later on my intel, if you need
> 
> Guess this would help as well :)

ok, I will write later to this issue

**Comment by ziarmandhost** [comment]
> > I dont have M1
> 
> Sorry. I misread.
> 
> > I could test later on my intel, if you need
> 
> Guess this would help as well :)

yes, it works good on INTEL!

**Comment by yandeu** [comment]
Thanks!

**Comment by murat-dogan** [comment]
Mac M1 support added on v0.3.6
