### ISSUE TITLE
EC2 deployment problems

### ISSUE THREAD

**Issue by ziarmandhost** [geckosio/geckos.io#221]
I done as you write in guide, but have a problem. 

### I have this setup: 
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/30569343/184243091-f9bd7d9f-ac9c-4eaa-b701-f9ea0ec480f5.png">

Then I run  my server like that:

### Backend code:
```
const io = geckos({ cors: { origin: "*", allowAuthorization: true } })
const PORT = 3000
io.listen(PORT)
```

### package.json

```"scripts": {
    "start-dev": "electron .",
    "dist-all": "electron-builder -wm"
  }
  ```

### In ssh tunel:
```pm2 start npm -- start```

Then I have this:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/30569343/184243447-02aa012b-c647-4781-ac68-4098952fee3b.png">

But game not started, because I'm not getting any messages between server and client. Please help, what could be wrong in my setup?

**Comment by ziarmandhost** [comment]
Amazon Linux (Inferred) Linux/UNIX
AMI name: amzn2-ami-kernel-5.10-hvm-2.0.20220719.0-x86_64-gp2
Instance type: t2.micro
Volume size (GiB): 8
Number of vCPUs: 1

**Comment by yandeu** [comment]
Electron on the backend? What is this for?

**Comment by ziarmandhost** [comment]
> Electron on the backend? What is this for?

sorry, wrong package.json, its client

```
"scripts": {
    "start": "npm-run-all --parallel dev:*",
    "dev:nodejs": "nodemon src/index.mjs"
  },
```

**Comment by yandeu** [comment]
Did you add ICE servers?
See: 
 - https://github.com/geckosio/geckos.io#ice-servers
 - https://youtu.be/Y1mx7cx6ckI

---

What is the JSON response in `remote-description` and the first `additional-candidate`?

**Comment by ziarmandhost** [comment]
> Did you add ICE servers? See:
> 
> * https://github.com/geckosio/geckos.io#ice-servers
> * https://youtu.be/Y1mx7cx6ckI
> 
> What is the JSON response in `remote-description` and the first `additional-candidate`?

but I'm making game, not a chat or video chat, do I still need ICE servers?

**Comment by ziarmandhost** [comment]
> Did you add ICE servers? See:
> 
> * https://github.com/geckosio/geckos.io#ice-servers
> * https://youtu.be/Y1mx7cx6ckI
> 
> What is the JSON response in `remote-description` and the first `additional-candidate`?

adding ICE server works for me, thanks!
