### ISSUE TITLE
Multiplex all Peer Connections on the same UDP

### ISSUE THREAD

**Issue by auberryberry** [geckosio/geckos.io#228]
From what I can see some folks are struggling with how to run geckos.io in production, and for sure, this is tricky; while the initial connection can happen via NLB or ALB  on AWS, whatever you're running this on will need a full range of UDP ports available and routable.  This is pretty difficult unless you massively slim down the port range; even then, FarGate starts to hit 100 port limits etc.

Quickly you end up with a full-blow k8s setup and some sort of stateful routing to get back to the same server instance.  What would be very cool, and now it's in node-datachannel is enabling multiplexing of UDP ports, so in theory, we could just use one port, which makes the network setup much less fiddly.

Super happy to pull together a PR to do this myself, or if you wanted to pick it up, cool.

https://github.com/murat-dogan/node-datachannel/issues/121
https://github.com/paullouisageneau/libdatachannel/pull/570

**Comment by yandeu** [comment]
Oh wow. I did not know it does now support multiplexing.
Would be happy to see a PR :)

**Comment by auberryberry** [comment]
You got it @yandeu, give me a day or two, are you happy for a new port property in the config, and then based if that is set or the range is set, we can configure node-dataport the right way?

**Comment by yandeu** [comment]
Yes, a new port property in the config would be nice.

**Comment by auberryberry** [comment]
FYI, just getting back to this, should be done in the next couple of days with any luck!

**Comment by arthuro555** [comment]
@auberryberry Are you still working on this? It would be so useful for geckos to get this feature 🙏

**Comment by auberryberry** [comment]
Yep, sorry, I can get this finished this week I think, just a bazillion things needed doing and got in the way. I have the infra to test now, let me get on it.
________________________________
