### ISSUE TITLE
Any way to run a client in a Node app?

### ISSUE THREAD

**Issue by haydenjameslee** [geckosio/geckos.io#23]
Is there any way to run a client in a Node app? I'm trying to make "bots" that emit messages for an end-to-end test system, without a browser involved.

Thanks!

**Comment by yandeu** [comment]
No, but you could use electron with `new BrowserWindow({ show: false })` or puppeteer with `await puppeteer.launch({ headless: true })`.

- There an [example with electron](https://github.com/geckosio/geckos-with-electron).
- And [here one with puppeteer](https://github.com/geckosio/phaser3-multiplayer-game-example), which adds bots with `npm run test`.

**Comment by haydenjameslee** [comment]
Thanks! Will have a go at something like that. And thanks a bunch for this repo, I've been doing WebRTC for a few years and have always wanted to mess around with client-server topologies.

**Comment by bennlich** [comment]
@yandeu do you have any recommendations for how to run a stress test? I'm working on a multiplayer game and want to figure out how many concurrent clients I'll be able to support. E.g. any idea if it would be reasonable to open ~500 puppeteer chrome tabs on the same machine and point them to my game server?

**Comment by bennlich** [comment]
So far I've been able to successfully spawn ~200 puppeteer windows :+1:
