### ISSUE TITLE
OpenSSL or GnuTLS installation

### ISSUE THREAD

**Issue by ddhaiby** [geckosio/geckos.io#238]
Hey there! This is half a bug report half a suggestion for those who would have issues with installation. It seems that I needed to install OpenSSL or GnuTLS to have all the include files. So I would suggest to have the following sentence in your readme (not an expert with Pull Requests)

Make sure to install either [OpenSSL](https://www.openssl.org/) or [GnuTLS](https://www.gnutls.org/) that will be used to setup WebRTC (see https://github.com/paullouisageneau/libdatachannel).

Thank you!

**Comment by yandeu** [comment]
Thanks. Can you make a PR for that?
