### ISSUE TITLE
Port range should be 1-65535

### ISSUE THREAD

**Issue by Quitalizner** [geckosio/geckos.io#239]
Here's a snippet from the Readme section.

  You have to make sure you deploy it to a server which forwards all traffic on ports 9208/tcp (or another port you define) and 0-65535/udp to your application.
  
  Port 9208/tcp (or another port you define) is used for the peer signaling. The peer connection itself will be on a random port between 0-65535/udp.

It is mentioned that we have to open 0-65535/udp. But the port 0 cannot be opened on firewall as it is considered a virtual port.
Shouldn't the readme be updated to 1-65535?

**Comment by yandeu** [comment]
Actually it should be 1025-65535.

**Comment by Quitalizner** [comment]
Hmm, interesting. Should we specify that in portRange property in geckos API or is that the default value?

**Comment by yandeu** [comment]
> Should we specify that in portRange property in geckos API or is that the default value?

No, you're right. This should be changed as well.

**Comment by Quitalizner** [comment]
Perfect thank you
