### ISSUE TITLE
[Client side]: Closed 'channel' still triggers events.

### ISSUE THREAD

**Issue by ohmed** [geckosio/geckos.io#24]
After using 'channel.close()' on client side and establishing new connection, all events [message/connect/etc] are not triggered twice.
Just need to clear internal array of event-handler functions.

**Comment by yandeu** [comment]
Can you share an simple example?

Is it something like this? Where onConnect is only triggered once?

```ts
import geckos from '@geckos.io/client'

let channel = geckos({ port: 3000 })

channel.onConnect(error => {
  if (error) {
    console.error(error.message)
    return
  } else {
    // "You are connected" is only triggered once
    console.log('You are connected')
  }
})

setTimeout(() => {
  console.log('Close')
  channel.close()
}, 2000)

setTimeout(() => {
  console.log('Open new Connection')
  channel = geckos({ port: 3000 })
}, 3000)

```

**Comment by yandeu** [comment]
Oh no wait! I guess I see it now. Is this the bug?

```ts
import geckos from '@geckos.io/client'

let channel
const connect = () => {
  channel = geckos({ port: 3000 })

  channel.onConnect(error => {
    if (error) {
      console.error(error.message)
      return
    } else {
      // "You are connected" is triggered twice on the second connection
      console.log('You are connected')
    }
  })
}
connect()

setTimeout(() => {
  console.log('Close')
  channel.close()
}, 2000)

setTimeout(() => {
  console.log('Open new Connection')
  connect()
}, 3000)
```

**Comment by yandeu** [comment]
[This](https://github.com/geckosio/geckos.io/commit/ef2cbf7dd0e09f74312e67060404558dab228047) should fix it, what do you think?

If you call channel.close(), the onDisconnect event fires, which will remove all listeners.

**Comment by ohmed** [comment]
Hey. Should fix it!
Will try today. And will give feedback :)

**Comment by ohmed** [comment]
Hey again. There's kinda small problem with disconnect.
When you want to assign callback for disconnect event, all listeners are dropped
```
  /**
   * Listen for the disconnect event.
   * @param callback The event callback.
   */
  onDisconnect(callback: ConnectionEventCallbackClient) {
    bridge.on(EVENTS.DISCONNECTED, callback)

    // remove all event listeners
    bridge.removeAllListeners()
  }
```
In Client.ts removes all listeners when adding handler and not when callback of disconnect fires.

**Comment by yandeu** [comment]
I have fix it. I will first make some test and then directly push it to npm in a few hours.

**Comment by ohmed** [comment]
Thx a lot for fast fixes 👍
