### ISSUE TITLE
onDisconnect doesn't get triggered when tab is closed

### ISSUE THREAD

**Issue by Quitalizner** [geckosio/geckos.io#242]
@yandeu,

I'm not sure if it's the implementation, the onDisconnect for the client channel in the server doesn't trigger when the tab is closed.
But when I refresh the game the onDisconnect does fire.

Can you please let me know if this is how it is implemented?

**Comment by yandeu** [comment]
The server should detect the disconnection after few seconds. Doesn't it work?

**Comment by Quitalizner** [comment]
Yeah, it does seem to disconnect after a while. Is there a way to make it instant?

**Comment by Quitalizner** [comment]
Okay, got it. Thank you
