### ISSUE TITLE
Reliable messages sometimes are processed multiple times

### ISSUE THREAD

**Issue by cfortuner** [geckosio/geckos.io#25]
Hi!

I am trying to use the reliable messages option for actions that should be processed exactly one time however I am noticing that the server sometimes processes these messages multiple times.

It's hard to reproduce because it's intermittent but I was just wondering if this is a supported feature?

Thanks!
Colin

**Comment by yandeu** [comment]
Each reliable message should only be processed once on the other side.

Do you use the default settings for the reliable messages?

By default the server receives up to 10 messages, but once one message passed, the server should reject the rest. 

Here is the code executed on the server when he receives a reliable message:
https://github.com/geckosio/geckos.io/blob/master/packages/server/src/wrtc/channel.ts#L256

Do you think there is a bug?

**Comment by cfortuner** [comment]
I think I see what is happening...let me know if this makes sense to you.

I am sending a reliable message with **undefined** data like this:
```
  channel.emit(eventName, undefined, {
          reliable: true,
          interval: 150,
          runs: 10,
        })
```
I think that this check will prevent these messages from being saved as reliable messages: 
```typeof data.MESSAGE !== 'undefined'```

https://github.com/geckosio/geckos.io/blob/620a75452877e31d117d7bd8af87508769ef4de2/packages/server/src/wrtc/channel.ts#L261

Is it necessary to check that data.MESSAGE is undefined here? 

Is it bad practice to send a message with only the eventName?

Thanks yandeu!

**Comment by yandeu** [comment]
I see. Yes, I guess this is the issue. I have never tried to send an undefined message. I will investigate this and make changes if needed.

Have you tried to send `null` instead? (No idea if it works). Anyways I will check it, and report back :)

**Comment by yandeu** [comment]
I have fixed it. But I guess I will not yet publish it to npm. Try to use `null` or `''` instead. Hope this helps :)
