### ISSUE TITLE
Command failed on node-datachannel connection while deploying to 'render' hosting service.

### ISSUE THREAD

**Issue by codernineteen** [geckosio/geckos.io#252]
**Describe the bug**
<img width="999" alt="스크린샷 2023-03-19 오전 9 29 37" src="https://user-images.githubusercontent.com/65900882/226147214-54cd54cd-5618-4602-9e3f-4d1812b01f44.png">

This is a capture of the error message i got from render.
All the settings for deployment is same when i tried to deploy socket.io server and it deployed successfully.
I think there is a problem in geckos's node_modules directory.

**Have a question?**
Join the [discussions](https://github.com/geckosio/geckos.io/discussions) instead.

**Comment by arthuro555** [comment]
This might be fixed by #254.
When NODE_ENV is set to production (common on such CD servers) and your node version does not have a prebuilt package available, the build command of node_datachannel was wrong and did not actually build the module on the fly properly.

**Comment by codernineteen** [comment]
Thanks, i will try it now
