### ISSUE TITLE
Command failed in regard to #254 pull request

### ISSUE THREAD

**Issue by codernineteen** [geckosio/geckos.io#255]
I checked the dependency of server package was updated by previous pull request(node-datachannel 0.4.1 -> 0.4.2).
But Was this reflected on latest version? Because when i re install library with 2.3.0 version using npm, the dependency of node-datachannel in server dir is still "0.4.0" version so that it still causes 'Command failed' error.

**Comment by yandeu** [comment]
Has been fixed in https://github.com/geckosio/geckos.io/commit/0882d63948213781cc89a53149cde7597c24dd40.
