### ISSUE TITLE
What happens to client connections when I refresh the browser?

### ISSUE THREAD

**Issue by cfortuner** [geckosio/geckos.io#26]
Hey!

I hope you're doing well. Thanks for working on this library. It works great!

I just had a question about the behavior of channels when the client refreshes the window? Is there any way for the server to listen for this event or check if a channel is no longer active?

I'm noticing that refreshing the browser doesn't trigger an 'onDisconnect' event on the server. Let me know if I'm missing something. 

Thanks!
Colin

**Comment by yandeu** [comment]
Hi,

Thanks :smiley: 

It should trigger the onDisconnect event, but it takes some seconds. Can you please check it again?

**Comment by cfortuner** [comment]
Interesting. I tried this again on version 1.5.0 and it seems like it's working. Yesterday I was having issues with 1.4.3?

Seems good for now!
