### ISSUE TITLE
 Generic type 'EventEmitter<EventTypes>' requires between 0 and 1 type arguments.

### ISSUE THREAD

**Issue by cfortuner** [geckosio/geckos.io#27]
node_modules/@geckos.io/server/lib/wrtc/channel.d.ts(11,19): error TS2707: Generic type 'EventEmitter<EventTypes>' requires between 0 and 1 type arguments.

Getting an error on the new version 1.5?

**Comment by cfortuner** [comment]
Also, I don't see the new `channel.onDrop` either. Has it been released?

**Comment by yandeu** [comment]
> node_modules/@geckos.io/server/lib/wrtc/channel.d.ts(11,19): error TS2707: Generic type 'EventEmitter' requires between 0 and 1 type arguments.

I guess this is the same as #22?



> Also, I don't see the new `channel.onDrop` either. Has it been released?

Yes, I just tested it and it works. Add the following to your server to test it:

```js
// server.js
const interval = setInterval(() => {
  channel.raw.emit(Buffer.alloc(32 * 1024))
}, 0)

setTimeout(() => {
  clearInterval(interval)
}, 5000)

channel.onDrop(drop => {
  console.log(drop.reason)
})
```

**Comment by cfortuner** [comment]
https://github.com/primus/eventemitter3/pull/224

I was able to fix this by manually installing eventemitter3@4.0.4. (I uninstalled after and then my package lock was able to use 4.0.4 for geckos.) For some reason, `npm upgrade geckos@1.5.0` didn't respect the ^4.0.0 [here](https://github.com/geckosio/geckos.io/blob/6e994581198eacfe3d13b4538e90e5e95776254c/packages/server/package.json#L45) and fetch the latest version of eventemitter3@4.04

This isn't an issue for me anymore but I'd be curious if you might know why this happened?

**Comment by cfortuner** [comment]
Also, I am now seeing onDrop! Thanks.
