### ISSUE TITLE
Simple Ack system

### ISSUE THREAD

**Issue by cfortuner** [geckosio/geckos.io#28]
Hi!

I noticed that the user cannot acknowledge / respond to messages when they are tabbed out (in a different tab / window). 

When my player connects, the client / server perform a handshake using the reliable message protocol  however if the client switches tabs / windows for longer than the reliable message time (ex. 50 attempts, once every 150 ms = 7.5 seconds) then they client will not be able to acknowledge the message.

This is a small issue and can be avoided in other ways however,  I think it would be very valuable to have a lightweight 'ack' system on top of both the reliable / unreliable geckos messaging like the system described here https://gafferongames.com/post/reliability_ordering_and_congestion_avoidance_over_udp/

There are a few cases in addition to the reliable messaging case that this would be very helpful / important so I just wanted to see if it was something you would consider? 

I'd be happy to help work on this with you!

**Comment by yandeu** [comment]
Can you share your code?

I just tested it with chrome and firefox and it worked well. I opened new tabs, opened other programs and when I came back, everything worked as expected.

I did this:
```js
// client
channel.on('reliable message', message => {
  console.log('Say', message)
})

// server
setInterval(() => {
  channel.emit('reliable message', 'hello!', { reliable: true })
}, 1000)
```

**Comment by cfortuner** [comment]
Oops! My fault. I had an error but it wasn't due to the reliable messaging. I was able to test that this worked correctly.

I am curious about your thoughts on an acknowledgment system? But I can close this now. Sorry for the bad issue!!

**Comment by yandeu** [comment]
> I am curious about your thoughts on an acknowledgment system?

Geckos.io is really only meant to be used in-game. It is build to be fast and therefore unreliable. If you use geckos.io, you always have to consider packages loss (even with reliable messages). If you are in the game lobby, menu or send important state updates at the end of a round, I consider making simple http request instead.

If the player, as you wrote, changes tab, he is not really in-game.
