### ISSUE TITLE
Geckos client and server not connecting anymore. Even on local machine

### ISSUE THREAD

**Issue by Quitalizner** [geckosio/geckos.io#283]
I'm working on a platform shooter for quite some time now using geckos and phaser.
I returned after a 2-month break as I was working on other projects. Everything was stable when I left. I even deployed it to production with everything working fine.

I check the prod link and the server doesn't connect. I go and check in the server and the process is running fine.

So I try to check if the browser updates have affected connection somehow, so I run the server on my local machine and it won't connect.

I've attached the screenshot of the error

![image](https://github.com/geckosio/geckos.io/assets/30500140/66ebbad5-883d-49ae-a6c3-46b986765e06)
I suspect it has something to do with the browser. I tried on Brave, Chrome and Firefox. None of them work anymore

**Comment by reececomo** [comment]
The URL you are querying here looks like: `http://loca Multiplayer.ts:125 lhost/:3000/.wrtc/v2/connections`, have you accidentally copy-pasted something in the `host` field?

i.e. 
```json
{
  host: 'loca Multiplayer.ts:125 lhost`,
  port: 3000,
}
```

<img width="405" alt="Screenshot 2024-01-28 at 3 06 55 pm" src="https://github.com/geckosio/geckos.io/assets/7390781/2916c610-2cf4-422d-9d54-f9f91660c198">

**Comment by reececomo** [comment]
Is `localhost/:3000/` correct? Shouldn't it be `localhost:3000/`

**Comment by Quitalizner** [comment]
> Is `localhost/:3000/` correct? Shouldn't it be `localhost:3000/`

Oh, yeah. Thanks for pointing that out. I was changing things around to make it run and I must have added in the '/'
It does work on localhost now. I just need to figure out what's going on with prod.

I'll update here once I find out.

**Comment by reececomo** [comment]
All good, we all do it 🙉 

Could you post a stacktrace/error from the prod failure? Or maybe a snippet/screenshot of the connection code? It can be a rough draft

**Comment by Quitalizner** [comment]
<img width="728" alt="Screenshot 2024-01-28 at 4 02 07 PM" src="https://github.com/geckosio/geckos.io/assets/30500140/cf6c47f2-bbf2-445b-a95c-d411d7dc960c">

For the prod link.

**Comment by Quitalizner** [comment]
I figured out the problem. The domain was pointing out to a different server IP address 🤦
