### ISSUE TITLE
Newbie question about performance

### ISSUE THREAD

**Issue by bryanhpchiang** [geckosio/geckos.io#29]
Apologies if this a dumb question: I'm making a simple multiplayer game, need to synchronize player positions. So if I have N players, I'll have all the players join the same room. For each player, I'll send one position update at 20 times per second to the entire room. My concerns:

1. If I send a JSON containing { position }. Does geckos.io compress this into a binary format? Or does this even matter.
2. Should I be sending position updates, or maybe just inputs and keep track of player entities/positions/velocities on the server side?

Any thoughts/suggestions would be appreciated. Thanks.

**Comment by yandeu** [comment]
> If I send a JSON containing { position }. Does geckos.io compress this into a binary format?

No, geckos will send the stringified JSON. You can use the packages [@geckos.io/typed-array-buffer-schema](https://www.npmjs.com/package/@geckos.io/typed-array-buffer-schema) to convert your data to a buffer.

> Or does this even matter.

It does not always matter. If you send `{"id":0,"x":14.8,"y":97.1}` x 16 players x 20 fps, you are sending about 10 kilobytes per second per player. This is not much. If you use the library I mentioned above, you would only send about 3 kilobytes per second. Both, 10 and 3 are very low values.

> Should I be sending position updates, or maybe just inputs and keep track of player entities/positions/velocities on the server side?

The client usually only sends the inputs. An array of booleans would be nice.
```js
// keep track of the keys which are pressed
const keys = {
  left: true,
  right: false,
  up: false,
  down: false,
  space: true
}

channel.emit('inputs', [left, right, up, down, space])
```

**Comment by bryanhpchiang** [comment]
Thanks, that's really helpful! Just a few more questions:
1) So right now my basic engine looks like:

On the server side, I have a map of entities/players. When clients join/leave, I update the map accordingly. 20 times per second, the server will emit an event to all the clients in the room with all of the entity positions and rotations. The part I'm stuck on is on the client side, should I render my graphics whenever I get a new "update" event from the server. Or should I run my own 20 times/second loop on the client side and read the latest server update when possible. 

Any thoughts would be appreciated - no physics or bullets involved at the moment, just player positions.

2) What's an acceptable throughput (i.e. upper limit) for each client in terms of receiving/sending updates? Or does CPU performance/rendering tend to be the limiting factor instead of network throughput.

3) This is a bit farther out, but how would I handle a simple physics collisions between players and objects (non-players). I'm guessing I would need to use some sort of physics engine on the server side (I saw your enable3d project), but my questions is that for players, I don't need to persist the player locations to some database. But for objects in a scene, if I want to persist that location across multiple sessions/restarts of the client and/or server, what should that flow look like?

Again, thanks for your help - apologies for these basic questions. Thanks!

**Comment by yandeu** [comment]
> The part I'm stuck on is on the client side, should I render my graphics whenever I get a new "update" event from the server. Or should I run my own 20 times/second loop on the client side and read the latest server update when possible.

You should run the client at 60 fps and update the positions as soon as you get them.  
But, if you want to make it professional, you would, on the client side, interpolate between the different positions to make the movement look smooth. Try [@geckos.io/snapshot-interpolation](https://www.npmjs.com/package/@geckos.io/snapshot-interpolation).

> What's an acceptable throughput (i.e. upper limit) for each client in terms of receiving/sending updates?

Difficult to say. Depends on your game. Start with a cheap server. Update the server or optimize the throughput as needed.

> I'm guessing I would need to use some sort of physics engine on the server side

Yes, you should run the physics on the server (if physics is really needed for you game). Use a 2d or 3d physics engine of you choice. (Is your game 2d or 3d? What kind of game are you making?). Normally your server could run for days without a restart. So there is no need to store positions in a database. Why would you want to keep the state of world objects even after a server restart? You could do it of course very simple: Just write the position and rotation of all objects to a json file which you store on your disk.

**Comment by bryanhpchiang** [comment]
Great, thanks. Very helpful!
