### ISSUE TITLE
Firefox onRaw problem.

### ISSUE THREAD

**Issue by ohmed** [geckosio/geckos.io#3]
Hey, noticed a problem when using raw data for Firefox.

After small investigation got this:
```dataChannel.onmessage = function (ev)```
in Chrome ```en.data``` is ```ArrayBuffer```.
in Firefox ```en.data``` is ```Blob```

So in result getting errors about messageParsing.
This is fixable if add
```dataChannel.binaryType = 'arraybuffer';```
[in connectionManager file]

**Comment by yandeu** [comment]
Hi,
Sorry for the delay. I was just moving to another place, including my office. At the same time I was moving from Ubuntu to Windows with WSL. I'm still not 100% comfortable with the new setup, but I want to let you know that I will be into this issue in the next few days.

BTW I like your DatTank game :)

**Comment by yandeu** [comment]
I have made the changes you suggested. Can you test it?

**Comment by ohmed** [comment]
Yeah, I made this change. Works perfect. Also I made some other change, for disconnection of user.
Cause 'disconnect' was not always triggering.
I can make later a PR with this changes when will have some free time.

**Comment by yandeu** [comment]
> I can make later a PR with this changes when will have some free time.

This would be very nice, thanks :)

**Comment by speekadievs** [comment]
@ohmed Hey, could you point to a direction on where did you make this change for disconnection of users? I would be glad to make PR
