### ISSUE TITLE
Authorization and Authentication

### ISSUE THREAD

**Issue by caracal7** [geckosio/geckos.io#30]
Especially im interesting reconnecting and re-login on mobile then the app goes idle for a long time and go back online.

And is it possible to establish HTTPS connection to geckos server?

p.s. Tnx 4 the great library!

**Comment by yandeu** [comment]
There is not built-in auth system, but you can easily add your own using jwt or any other system.

Yes, this is possible. Take a look at the [server section](https://github.com/geckosio/geckos.io#servers).

_You're welcome :)_

**Comment by yandeu** [comment]
I thought about it. I guess a integrated auth system would be nice. Opening a dataChannel is not cheap and if we could prevent unauthorized users from connecting, it would be great. I will see what I can do.

**Comment by yandeu** [comment]
I have added an auth implementation. Take a look at the [readme](https://github.com/geckosio/geckos.io#readme) file.

What do you think? Is this what you had in mind?

**Comment by caracal7** [comment]
Thanks for wasting you time for this.

I think is better to put encoding/decoding inside geckos. Why do you think to give encoding/decoding to user?

Something like:

**client**
```
const channel = geckos({ username: 'Yannick', password: 'I2E4S' })
```

**server**
```
const io: GeckosServer = geckos({
  authorization: async (username: string, password:string) => {
     // ...
     return username == 'Yannick' && password == 'I2E4S' ? true : false; 
  }
});
```

**Comment by yandeu** [comment]
Well, the example I've implemented shows how to use the standardized authentication scheme 'Basic'. But you could of course just send a simple string. I do not want to implement encoding/decoding, because everyone is doing it differently. 

I have update the readme, please check it.

**Comment by yandeu** [comment]
I have just released v1.6.0.

Do you have some questions regarding it? Or can we close this issue?

**Comment by andrewmunro** [comment]
@yandeu It's funny, was just chatting about this with a friend and turns out you added it days ago! This is exactly what we need. I agree with you around standardising on an Authorization header, seems quite clean. 

>  I do not want to implement encoding/decoding, because everyone is doing it differently
This. We'll probably end up sending a JWT or something. If you keep it as a string, everyone can implement their own encoding.

**Comment by caracal7** [comment]
> Do you have some questions regarding it? Or can we close this issue?
No. Everything is clean)
I will try authentication at weekend.

**Comment by yandeu** [comment]
> Have you thought about making it possible to return that data to the user in the handshake?

This is a great idea! I have just implemented. See (d981f75cbf08ecb106728fc6251ef973d5a4c364)

**Comment by andrewmunro** [comment]
> > Have you thought about making it possible to return that data to the user in the handshake?
> 
> This is a great idea! I have just implemented. See ([d981f75](https://github.com/geckosio/geckos.io/commit/d981f75cbf08ecb106728fc6251ef973d5a4c364))

😍😍😍
