### ISSUE TITLE
Missing channel.id

### ISSUE THREAD

**Issue by cfortuner** [geckosio/geckos.io#31]
Hey! Hope you're doing well. I was just wondering why the channel id is sometimes missing after connecting?
Thanks!

```
channel.onConnect((error: any) => {
      ... 
      if (!channel.id) {
        console.error('Error! Missing channel id')
        return
      }
}
```

**Comment by yandeu** [comment]
I guess this (707cc7ff13ed9f1ab45c7daa833367779e84160e) fixed it. If the dataChannel was ready quickly, onConnect was called before the id was set.

What do you think?

**Comment by cfortuner** [comment]
Yeah this seems reasonable! Thanks!!
