### ISSUE TITLE
Client disconnect detection on browser window reload

### ISSUE THREAD

**Issue by Chroma72** [geckosio/geckos.io#32]
Is there a way to set the client timeout? I'm trying to catch when the client clicks refresh as fast as possible and disconnect them. Any help is greatly appreciated.

**Comment by yandeu** [comment]
You mean a client timeout on the server?
If you refresh, you instantly want to disconnect the user from the server?

Well, WebRTC handles the disconnection events automatically. This can take some seconds.

You could implement your own strategy. For example sending a ping from the client to the server x times per seconds. If the server does not get a single ping for x seconds, call `channel.close()` on the server.

---

But you just gave me an idea. I guess with the new **Authentication** feature, it will easily be possible to detect if a user did reconnect. So if the serve sees a open connection for that user, it would be possible to close it immediately. I will try it today.

**Comment by yandeu** [comment]
Yes, it did work:
_Will work for you in the next version of geckos.io (>=1.6.0)_

client
```js
// some unique id you store in localStorage
const channel = geckos({ authorization: 'some-unique-random-id' })
```

server
```js
const io: GeckosServer = geckos({
  authorization: async (header: any) => {
    // this will set channel.userData to { token: 'some-unique-random-id' }
    return { token: header }
  }
})

io.onConnection((channel: ServerChannel) => {

  // look if there is already a connection with the same token in userData
  io.connectionsManager.getConnections().forEach(c => {
    const { id, userData } = c.channel.webrtcConnection

    // same token for a different channel id?
    if (userData.token === channel.userData.token && id !== channel.id) {

      // close the connection immediately (does not send events, but it's fast)
      io.connectionsManager.deleteConnection(c)

      // call c.close() if you want to see all events (not as fast)
      // c.close()

      // show how many active connections we have
      console.log('active channels', io.connectionsManager.getConnections().size)
    }
  })
...
```

I guess this is what you where looking for?

**Comment by Chroma72** [comment]
That is great, thanks for your help.

One more question: I'm having trouble getting @geckos.io/server up and running on glitch.

When I do this:
`const geckos = require('@geckos.io/server').default;
const io = geckos();
io.listen();`

 I get the following:
`internal/modules/cjs/loader.js:613
    throw err;
    ^
Error: Cannot find module '../build/Release/wrtc.node'
Require stack:
- /rbd/pnpm-volume/71bd0c1a-de11-47fa-986b-650aec5eb6ea/node_modules/.registry.npmjs.org/wrtc/0.4.5/node_modules/wrtc/lib/binding.js
- /rbd/pnpm-volume/71bd0c1a-de11-47fa-986b-650aec5eb6ea/node_modules/.registry.npmjs.org/wrtc/0.4.5/node_modules/wrtc/lib/index.js
- /rbd/pnpm-volume/71bd0c1a-de11-47fa-986b-650aec5eb6ea/node_modules/.registry.npmjs.org/@geckos.io/server/1.5.0/node_modules/@geckos.io/server/lib/wrtc/webrtcConnection.js
- /rbd/pnpm-volume/71bd0c1a-de11-47fa-986b-650aec5eb6ea/node_modules/.registry.npmjs.org/@geckos.io/server/1.5.0/node_modules/@geckos.io/server/lib/wrtc/connectionsManager.js
- /rbd/pnpm-volume/71bd0c1a-de11-47fa-986b-650aec5eb6ea/node_modules/.registry.npmjs.org/@geckos.io/server/1.5.0/node_modules/@geckos.io/server/lib/server.js
- /rbd/pnpm-volume/71bd0c1a-de11-47fa-986b-650aec5eb6ea/node_modules/.registry.npmjs.org/@geckos.io/server/1.5.0/node_modules/@geckos.io/server/lib/index.js
- /app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/71bd0c1a-de11-47fa-986b-650aec5eb6ea/node_modules/.registry.npmjs.org/wrtc/0.4.5/node_modules/wrtc/lib/binding.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)`

Any ideas? I checked the npm version and it's:
`  "engines": {
    "node": "12.x"
  },`

**Comment by yandeu** [comment]
wrtc.node uses c++ code and geckos.io uses UDP ports. I guess both do not work on glitch. It will also not work on heroku or similar services.

To make it work, you have to deploy it on a "real" server.

**Comment by Chroma72** [comment]
Ok got. Thanks!

**Comment by Chroma72** [comment]
Just wanted to share a quick fix for instant client disconnect detection:

In the client I put a:
`window.onbeforeunload = function(e) {`
`  channel.emit('refresh-close', 0, { reliable: true });`
`};`

and then on the server side a:
`channel.on('refresh-close', () => {`
`  channel.close();`
`});`

When the channel closes it drives the channel.onDisconnect which is just great! Instant client disconnect on client refresh and browser closing.

**Comment by Chroma72** [comment]
Ahhhh....this is just as effective and only on client side:
`window.onbeforeunload = () => {`
`  channel.close();`
`};`

**Comment by yandeu** [comment]
Thanks for sharing your snippets :smiley:
