### ISSUE TITLE
Access channel from IO scope

### ISSUE THREAD

**Issue by Chroma72** [geckosio/geckos.io#35]
I'm trying to access a channel id from the `io` scope to send a message (right before they get kicked haha!):
`io.channel[player.id].emit('chat message', 'You have been kicked for cheating!');`
And player.id is just the channel.id. But the above is not working. Is there a way to access a specific channel by id from the `io` scope?

This does work:
`io.channel[player.id].close();`

**Comment by yandeu** [comment]
I have not yet implemented a nice helper for it, but you can get the connection via the connectionsManager and then emit a message to its channel.

```ts
const connection = io.connectionsManager.getConnection(channel.id)
if (connection) {
  connection.channel.emit('chat message', 'You have been kicked for cheating!')
}
```

**Comment by yandeu** [comment]
> This does work:
> `io.channel[player.id].close();`

Use `connection.channel.close()` instead.

**Comment by Chroma72** [comment]
Works like a charm. Thanks!
I'm also trying to get the IP so I can have a 5 minute kick and then a permanent ban. Is there's a way to get the channel IP?

**Comment by yandeu** [comment]
No, this is not possible yet.

But I guess I could forward the http request to the authentication function? Then you could get the ip using `request.connection.remoteAddress` or `request.headers['x-forwarded-for']` (if behind a proxy).

Or you could store a unique key in localStorage and authenticate the user with it using the new authorization process.

_Btw, thanks a lot for your sponsorship! It really helps a lot_ :smiley:

**Comment by Chroma72** [comment]
Either would be great but getting the IP is more intuitive IMO.

Hey it's my pleasure. It's a great lib and it's really making my game awesome! :)

**Comment by yandeu** [comment]
Done! Take a look at https://github.com/geckosio/geckos.io/commit/d93c803dc4ab4646bba82b925ce82756aa7103b9.
Also take a look at the updated README file.
I think this is a good solution. What do you think?

**Comment by yandeu** [comment]
Will publish it soon to npm.
