### ISSUE TITLE
Client connect to IP address

### ISSUE THREAD

**Issue by Chroma72** [geckosio/geckos.io#36]
I'm trying to connect to an IP address and not having any luck yet. I've tried:
`channel = geckos({ url: "http://75.276.98.105", port: 9208 });`
`channel = geckos({ url: "75.276.98.105", port: 9208 });`
None of the above works.

BTW, that's a fictitious IP. I'm using my real IP and forwarded port 9208 (TCP/UDP) when I test it.

**Comment by Chroma72** [comment]
Dang! Just realized that its:
`channel = geckos({ url: "//75.276.98.105", port: 9208 });`

Sorry! 😳

**Comment by yandeu** [comment]
Do you get a response if you send a POST request to `http://75.276.98.105:9208/.wrtc/v1/connections`?

Or `http://75.276.98.105/.wrtc/v1/connections`?

**Comment by Chroma72** [comment]
False alarm. This was actually my fault. This does work:
`channel = geckos({ url: "http://75.276.98.105", port: 9208 });'

But clicking refresh wasn't allowing the client to reconnect because they were still connected. Had to retool the disconnect part of the client to fix it. Everything is working good now. Thanks for the quick response!
