### ISSUE TITLE
Reduce number of HTTP requests to establish a connection

### ISSUE THREAD

**Issue by Hughp135** [geckosio/geckos.io#37]
Firstly, just want to say thank you for making this great package!

In order to establish a connection, the client sends off many HTTP requests per ice candidates, which seems like it could cause more traffic than necessary if you're scaling up big.

Would it be worth considering ways to reduce the amount of network requests for the process? Possible solutions I could think of would be

1) Use websockets for the signalling server (slightly reduced overhead compared to fetches?)
2) Throttle ICE candidate requests, e.g. sending multiple candidates in 1 request. 
3) Allow users to implement their own signalling server. Expose methods such as 'onIceCandidate' and 'makeOffer' that can be called by gecko.
4) Some other way? To be fair I haven't looked into the source code too in depth, this is more from experience of using wRTC before and trying to find ways to optimize it.

**Comment by yandeu** [comment]
I guess the code could be improved to reduce the amount of fetches. IMO a good solution would be to delay the answer on the server until new ice candidates are found or if it reaches the timeout.

I will try to implement this strategy. I guess it will solve this issue.

**Comment by yandeu** [comment]
This (https://github.com/geckosio/geckos.io/commit/cdf0d7263e48a49668a95c9d3f026ac853062a0a) seems like a good solution.
