### ISSUE TITLE
Types.ConnectionEventCallbackServer - channel is 'any' type

### ISSUE THREAD

**Issue by Hughp135** [geckosio/geckos.io#38]
The type for `channel` in the callback passed to `io.onConnection` has the `any` type, so unless you manually cast it to a `ServerChannel`, you won't have access to the type definitions on the channel your working with.

E.g.:

```
io.onConnection((channel) => {
 // channel has type 'any'
}

```
It might be worth moving the type declaration into the server package so that the right type of 'channel' can be used by default.

If it is not possible to move the type def into the server package, you could make `ConnectionEventCallbackServer` have a generic type and pass it in on the server code. E.g.

`packages/common/src/types.ts`
```
export interface ConnectionEventCallbackServer<T = any> {
  (channel: T): void
}
```

`packages/server/src/geckos/server.ts`
```
onConnection(callback: Types.ConnectionEventCallbackServer<ServerChannel>) {
    bridge.on(EVENTS.CONNECTION, (channel: ServerChannel) => {
      let cb: Types.ConnectionEventCallbackServer<ServerChannel> = channel => callback(channel)
      cb(channel)
    })
  }
```

**Comment by yandeu** [comment]
Thanks a lot.

I think I will go for a even simpler solution. Deleting the `ConnectionEventCallbackServer` completely.

```ts
onConnection(callback: (channel: ServerChannel) => void) {
  bridge.on(EVENTS.CONNECTION, (channel: ServerChannel) => {
    let cb: (channel: ServerChannel) => void = channel => callback(channel)
    cb(channel)
  })
}
```
