### ISSUE TITLE
Improve performance of send

### ISSUE THREAD

**Issue by andrewmunro** [geckosio/geckos.io#41]
We are trying to optimize our game server and after doing some profiling we have realized sendMessage could be improved a little.

![image](https://user-images.githubusercontent.com/1107388/88951884-82cec780-d28e-11ea-88cc-99c6a4e1616a.png)

It looks you calculate the size of the message every time (I assume to ensure you don't overflow the buffer?):
https://github.com/geckosio/geckos.io/blob/master/packages/common/src/sendMessage.ts#L13

Given that our data is an arrayBuffer, you can simply do: `data.byteLength` to avoid the calculation...

Here's our code:

```
	protected emit(data: ArrayBuffer) {
		this.bytesOut += data.byteLength;
		this.socket.raw.emit(data);
	}
```

**Comment by yandeu** [comment]
Thanks!

No, it's used to avoid sending a too large message. WebRTC on node can (usually) send up to 256 kB per message. When I added the dependency `object-sizeof`, I wasn't sure if it is really needed. But I guess, no one tries to send messages that big for a game.

I guess replacing `object-sizeof` by `const bytes = data.byteLength ?? data.length * 2` is the easiest way.

What do you think?

Check https://github.com/geckosio/geckos.io/commit/539f91efaca19ebecede9d669b94ec8279e96b3f.

```ts
const send = (data: any) => {
  const bytes = data.byteLength ?? data.length * 2 // (times 2 for special characters that uses 2 bytes per char)

  if (typeof maxMessageSize === 'number' && bytes > maxMessageSize)
    throw new Error(`maxMessageSize of ${maxMessageSize} exceeded`)
  else dataChannel.send(data)
}
```
