### ISSUE TITLE
error 'Something went wrong in "await connectionsManager.connect()"  in 1.6.1.min.js

### ISSUE THREAD

**Issue by x1911** [geckosio/geckos.io#42]
here is the client side code, just like the example simple

`        
<script src="lib/geckos.io-client.1.5.0.min.js"></script> 
`
`
        <script>
            'use strict'
      
            var channel = geckos({ port: 2001 })
      
            channel.onConnect(error => {
              if (error) {
                console.error(error.message)
                return
              }
      
              channel.on('chat message', (d) => {
                channel.emit('chat message 2', 'Hello 2')
                console.log('get message', d)
              })
      
              channel.emit('chat message 1', 'Hello 1')
            })
          </script>`

after change to 
![image](https://user-images.githubusercontent.com/8219031/89116572-425a8e00-d4c8-11ea-9195-015c435d6aa0.png)

it shows 

![image](https://user-images.githubusercontent.com/8219031/89116586-5ef6c600-d4c8-11ea-9583-d6fa4a1b633e.png)

the server runs fine with both, no error came out

or did i miss something in version 1.6?

**Comment by yandeu** [comment]
I have just updated the simple example to geckos.io v1.6.1.

If you change the port on the client, you have to change the port on the server as well.

**Comment by x1911** [comment]
yeah, i also changed the server side, 

the simple example is here

https://github.com/geckosio/geckos.io/blob/master/test/e2e/simple.html

and after check the client example, still came the error message, but it works fine

another question, in the connectionsManager cant find all channel,

io.connectionsManager.connections  seems not same as channel, 

because i set the channel.userData,  in io.connectionsManager.connection is still undefined.

sorry for my poor english....

**Comment by x1911** [comment]
i got a solution, put the connection.userData = channel.userData


`
    io.onConnection(channel => {

        const connection = io.connectionsManager.getConnection(channel.id)
        if (!connection)  return 
        connection.userData = channel.userData

})
`

so is fine in the iteration of io.connectionsManager.connection

**Comment by yandeu** [comment]
Each connection has one channel.

Try `connection.channel.userData`

**Comment by x1911** [comment]
got it :)  👍 thanks



and the error message is from

packages/client/src/wrtc/peerConnection.ts : 23

this.localPeerConnection is undefined, its ok with them?

anything else works very well

**Comment by x1911** [comment]
every thing runs very smooth in ver. 1.7.0, and no more error or warning in console,
here is my new project: https://lagogo.dogfightx.com
and the url is not set.

but in some server must input the url, otherwise the client side cant connect the server,
here is  http://101.132.194.163:2001/c2/
if not set the url: 'http://0.0.0.0',  client stuck in first connect, is some how setting with the server?

**Comment by yandeu** [comment]
> every thing runs very smooth in ver. 1.7.0

Nice :smiley: 

I do not understand your question. Do you still experience some issues? Can you please elaborate?

**Comment by x1911** [comment]
the setting from client side:
` 
       const options = {
            port: 2001,
            portRange: {  // 1.7 ver
                min: 40000,
                max: 50000
              },
        }
       const channel = geckos(options)  // start channel
`

this setting works in serverA, but not works in serverB, (both servers are debian and use pm2, node14)

in serverB must add url parameter

`
       const options = {
            url: 'http://0.0.0.0',
            port: 2001,
            portRange: {  // 1.7 ver
                min: 40000,
                max: 50000
              },
        }
       const channel = geckos(options)  // start channel
`

then works serverB with this setting.  (both servers are unlimited by UDP connection)

**Comment by yandeu** [comment]
Why don't you just use a different port?

**Comment by DolphinIQ** [comment]
Hey, Im also having the same error when trying to upgrade from 1.3.0 to 1.7.0, running on a local environment
![image](https://user-images.githubusercontent.com/34486337/96903824-9ad17400-1496-11eb-9964-b1f266abd943.png)

My code (the relevant parts):
client: 
```
this.channel = geckos({
                port: 3000
            });

            this.channel.onConnect( error => {

                if( errorOccured( error ) ) {
                    // This console logs the error above
                    return;
                }

```

server:

```
const geckos = require('@geckos.io/server').default;
const { iceServers } = require('@geckos.io/server');

io = geckos({
    iceServers: process.env.NODE_ENV === 'production' ? iceServers : []
});

// express server
const PORT = 3000;
let server = app.listen( process.env.PORT || PORT, () => {
   console.log(`Server started on port ${ PORT }...`);
});
io.addServer( server );
```

Not sure what Im doing wrong, tried switching ports, and stuff from this thread with no success. Is there a migration guide?
