### ISSUE TITLE
How to set up a server

### ISSUE THREAD

**Issue by Chroma72** [geckosio/geckos.io#45]
I shelved my project for a bit because I couldn't find a host that would let me use UDP ports. Also tried to set up a server myself on a spare computer from my home (did the port forwarding). I'd really like to continue my project. Do you have any pointers? Or perhaps know how DatTank.io is using geckos.io and on what host?

Any help or information would be greatly appreciated.

**Comment by yandeu** [comment]
I don't know where DatTank is hosted.

I personally almost always use AWS EC2.

But AWS Lightsail and DigitalOcean work as well.

DigitalOcean has good tutorials:
- https://www.digitalocean.com/community/tutorials?q=Node

**Comment by bryanhpchiang** [comment]
Would recommend renting out a VPS from a cloud provider (AWS, GCP). Search for firewall settings, expose the UDP ports, and you should be good to go.

Less involved solutions like GAE / AWS EB are more risky, I personally wouldn't waste time trying to configure these.

**Comment by Chroma72** [comment]
So I ended up going with AWS Lightsail. Seems pretty straightforward and opening the necessary ports was a breeze. Just using the $3.50 a month for now until I get her up and running. I tried messing about with AWS EC2 but it seemed very obscure and not straightforward on how to deploy the files etc.

**Comment by yandeu** [comment]
Glad you found a way to run it!
