### ISSUE TITLE
Connecting through a load balancer

### ISSUE THREAD

**Issue by Jack-2025** [geckosio/geckos.io#46]
Hello everyone,

This is more of a question than an issue, but I'm not sure where else to post it.

I'm using an HTTPS load balancer on Google Cloud, with a VM group hosting geckos.io servers.

So I think the way it should work is for the browser geckos.io clients to negotiate the signals through the load balancer on HTTPS.  But because the load balancer does not seem to support UDP, the UDP communication has to occur directly between the browser and the VM.

The signaling seems to be reaching the VMs but the UDP communication is not occurring, even though the UDP ports are open.  It does work when connecting the client directly to the VM, but this is not usable in production for my case because mixed-mode (http & https) is blocked by the browser.

Does geckos.io support this scenario, or could you suggest an alternate way?

Thanks for developing this awesome package!!

**Comment by Jack-2025** [comment]
By the way, I'm using the following server options.

`const options = {
    portRange: {
        min: 1000,
        max: 1000
    },
    iceServers: null, iceServers
}
const io = geckos(options)`

**Comment by yandeu** [comment]
Each player uses one port (as far as I know). So `{ min: 1000, max: 1000 }` is not valid.
Just try the default options:
```js
const geckos = require('@geckos.io/server').default
const { iceServers } = require('@geckos.io/server')

const options = { iceServers }
const io = geckos(options)
```

---

I have just tested the [simple-chat-app-example](https://github.com/geckosio/simple-chat-app-example) with a nginx load balancer. It worked for me.

The example's geckos server is on port 3000 and the chat app on port 8080.

I just:
- set the url in **index.html** to the nginx server `var channel = geckos({ port: 3000, url: http://NGINX_SERVER_URL })`
- used the default iceServers in **server.js** `const io = geckos({ iceServers: iceServers })
`

On nginx, I forwarded both ports to the game server:
```nginx
server {
        listen 8080;
        location / {
                proxy_pass http://GAME_SERVER_URL:8080/;
        }
}

server {
        listen 3000;
        location / {
                proxy_pass http://GAME_SERVER_URL:3000/;
        }
}
```
I could reach the chat app on `http://NGINX_SERVER_URL:8080/`.

---

Just make sure your VM is reachable from the internet. Just for testing, try to open all ports (tcp and udp).

**Comment by Jack-2025** [comment]
Yandeu, thanks for the quick response!

I did the tweaks you suggested, and did manage to connect to the server through NGINX.

The setup I have is  browser -> google cloud HTTPS load balancer -> NGINX -> scalable group of VMs with node servers

If I understand correctly, the STUN server will return the load balancer's IP and the browser will try to send the UDP packets through it.  But that load balancer does not forward UDP packets, and I cannot ask the geckosio client to connect directly to the VM since that would result in mixing an HTTPS with an HTTP connection.

I wonder if there's a way around this with geckosio?

**Comment by yandeu** [comment]
_The thing with the nginx server was just for me to test. You do not really need one._

---

> If I understand correctly, the STUN server will return the load balancer's IP

No, the STUN server will return the VM's IP.

> load balancer does not forward UDP packets

Does not need to.

> if it's possible with geckos to do the signaling through the load balancer and the UDP transmission separately, by sending the packets to the VM's external IP rather than to the load balancer?

That is exactly what it does.

---

There will be no mixed content (http & https), only the signaling is done with http/https, the WebRTC connection itself does not use http nor https. Once the signaling is done, no UDP traffic will go through your LB.

Hope this helps :smiley:

**Comment by Jack-2025** [comment]
>The thing with the nginx server was just for me to test. You do not really need one.
Yes, I understand.  I was using NGINX myself but didn't bring it up on the initial post.

Alright I must have some small misconfiguration, but it's a relief knowing that's how it's supposed to work.  Thanks a lot for the help!!
