### ISSUE TITLE
Unable to include an URL path

### ISSUE THREAD

**Issue by Jack-2025** [geckosio/geckos.io#48]
There is a small issue when an URL with a path is used on the geckosio client constructor; the port number is appended as ":{port}" to the end of the path, when it should be added after the host name.

This can be worked around for the moment by disabling type checking and using for the port number a string as: "{port}/{path}"

**Comment by yandeu** [comment]
Since commit https://github.com/geckosio/geckos.io/commit/b03c52b504643982e756b91c1eba11f09362dd1d, you will be able to set the port to `null`. Then you could add the whole url (inclusive port and path) to `url`.
