### ISSUE TITLE
I am having worse performance and latency than websockets, can you advise?

### ISSUE THREAD

**Issue by sm64js** [geckosio/geckos.io#49]
I am testing a multiplayer game and trying to optimize online performance.

I have switched my game from websockets to use this library.  I believed using unreliable packets would get much better performance, however the performance is several times worse, latency is more than 100x higher.  Perhaps something is wrong.

This is the setup I am testing is where I have several very tiny messages being sent to each client every second.  1 message is sent for every player in the game, so for now I am testing 6-12 players, though I would like to do 100+

Each message is about ~100 bytes and I update at 30hz.
So with 10 players that is 100 bytes x 10 x 30 = 30000 = 30 KB/s

Pretty tiny right? The becomes a slideshow and unplayable. And I am testing all of this locally.

I understand I can make changes to this architecture and send all of the players in 1 message and that does increase performance as well as other changes that can increase performance.. but before I do that, I want to first understand and diagnose why the performance is worse than websockets. Because with the exact same setup, I get much better performance with sockets. So I want to figure out if something is not setup right.

Thanks

**Comment by yandeu** [comment]
What you describe here, should not generate a performance issue. Can you please share some of your code?

**Comment by sm64js** [comment]
Yes,

Server code is here:
https://github.com/sm64js/sm64js/blob/MMO_rewrite/serveProduction.js

and client code here:
https://github.com/sm64js/sm64js/blob/MMO_rewrite/src/socket.js

I'll go ahead and distill down the relevant parts and update this post.

**Comment by sm64js** [comment]
Distilled client code:
(Let me know if you want me to trim it down even more...)
```
import geckos from '@geckos.io/client'
import * as Multi from "./game/MultiMarioManager"

const channel = geckos()

export const networkData = {
    remotePlayers: {},
    mySocketID: -1,
}

export const gameData = {}

const sendDataWithOpcode = (bytes, opcode) => {
    const newbytes = new Uint8Array(bytes.length + 1)
    newbytes.set([opcode], 0)
    newbytes.set(bytes, 1)
    channel.raw.emit(newbytes)
}


const recvMyID = (msg) => { networkData.mySocketID = msg.id }


channel.onConnect(() => {

    channel.readyState = 1

    channel.onRaw((message) => {
        const start = performance.now()
        const bytes = new Uint8Array(message)
        const opcode = bytes[0]
        const msgBytes = bytes.slice(1)
        switch (opcode) {
            case 0: if (multiplayerReady()) Multi.recvMarioData(msgBytes); break
            case 9: recvMyID(JSON.parse(new TextDecoder("utf-8").decode(msgBytes))); break
            case 99: sendDataWithOpcode(new Uint8Array(), 99); break  ///ping pong
            default: throw "unknown websocket opcode"
        }
        const end = performance.now() - start
        //if (end > 100) console.log("Opcode: " + opcode + "  time: " + end +"ms  size: " + bytes.length)
    })

    channel.onDisconnect(() => { channel.readyState = 0 })
})

const multiplayerReady = () => {
    return channel.readyState == 1 && gameData.marioState && networkData.mySocketID != -1
}


//// this function gets called elsewhere right after the main game loop finished, this runs at 30fps
export const post_main_loop_one_iteration = (frame) => {

    if (multiplayerReady() && frame % 1 == 0) {
        sendDataWithOpcode(Multi.createMarioBinaryMsg(), 0) //// creates a binary message as Uint8 Array, that is ~100bytes
    }

}
```

**Comment by sm64js** [comment]
Distilled Server code: (Let me know if you want me to trim it down more)
```
const { MarioMsg, MarioListMsg, ControllerListMsg, ControllerMsg, ValidSocketsMsg } = require("./proto/mario_pb")
const fs = require('fs')
const util = require('util')
const zlib = require('zlib')
const deflate = util.promisify(zlib.deflate)
const geckos = require('@geckos.io/server').default()
const port = 9208


//// Sockets
const allSockets = {}

let currentId = 0
const generateID = () => {
    if (++currentId > 1000000) currentId = 0
    return currentId
}

const sendDataWithOpcode = (bytes, opcode, channel) => {
    if (bytes.length == undefined) bytes = Buffer.from(bytes)
    const newbytes = new Uint8Array(bytes.length + 1)
    newbytes.set([opcode], 0)
    newbytes.set(bytes, 1)
    channel.raw.emit(newbytes)
}

const broadcastDataWithOpcode = (bytes, opcode, channel) => {
    if (bytes.length == undefined) bytes = Buffer.from(bytes)

    const newbytes = new Uint8Array(bytes.length + 1)
    newbytes.set([opcode], 0)
    newbytes.set(bytes, 1)

    if (channel) channel.raw.broadcast.emit(newbytes)
    else geckos.raw.emit(newbytes)

}


const processPlayerData = (socketID, bytes) => {
    const decodedMario = MarioMsg.deserializeBinary(bytes)

    //Pretty strict validation  -- ignoring validation for now
    /*    ******* */

    //publish
    broadcastDataWithOpcode(bytes, 0, allSockets[socketID].channel)
}





/// Every 15 seconds
setInterval(() => {
    Object.values(allSockets).forEach(data => {
        data.channel.ping = process.hrtime()
        sendDataWithOpcode(new Uint8Array(), 99, data.channel)
    })
}, 15000)

geckos.onConnection(channel => {

    channel.my_id = generateID()
    allSockets[channel.my_id] = { valid: 0, channel }
    const responseMsg = new TextEncoder("utf-8").encode(JSON.stringify({ id: channel.my_id }))
    sendDataWithOpcode(responseMsg, 9, channel)

    channel.onRaw(bytes => {
        try {
            const opcode = Buffer.from(bytes)[0]
            switch (opcode) {
                case 0: processPlayerData(channel.my_id, bytes.slice(1)); break
                case 99:  ///ping pong
                    const hrend = process.hrtime(channel.ping)
                    console.info('Latency: %ds %dms', hrend[0], hrend[1] / 1000000)
                    break
                default: console.log("unknown opcode: " + opcode)
            }
        } catch (err) { console.log(err) }
    })


    channel.onDisconnect(() => {
        delete allSockets[channel.my_id]
    })
})




//// Express Static serving
const express = require('express')
const app = express()
const http = require('http')
const server = http.Server(app)
app.use(express.static(__dirname + '/dist'))

geckos.addServer(server)
server.listen(port, () => { console.log(' Listening to combined servers at ' + port) })
```

**Comment by sm64js** [comment]
Another pattern I noticed while testing was that it actually seems to do fine with 11 clients connected.  But once I add the 12th client, latency sky rockets, performance tanks.   Does this give you any clue to something that may be going wrong?

I'm also wondering, would there be any issues with my methods of testing this?  I am testing this with the server and all 12 clients on the same computer.  I know I am not getting performance issues from the computer being bottlenecked, because I  was able to run this same test and more with websocket libraries, and I can see CPU usage is not taking a hit.   But I wonder if something about having several webRTC connections all on the same computer or browser is doing something to throttle performance?

**Comment by sm64js** [comment]
I have been working on some more performance evaluation tests and have some more information, however the issues are still present.

The first test I explained was having the server and and 11 clients all on the same computer (that is has plenty of compute headroom), then as soon as I add the 12th client from that same computer... performance tanks and latency starts to snowball up to several seconds.

I setup this test again, except now having the server running a remote dedicated server.  I connect several clients all from the same local computer to that remote server... performance is similar but naturally latency is a little higher just because the server is remote, but it is reasonable (50ms).   The same behavior happens this time, except now the number of connections that causes everything to freak out and tank is slightly higher... now it is around 18 client connections when latency sky rockets.

I also tried a variety of tests where I would split up the clients across computers., say having 4 different computers each having 3 -4 clients.... the performance is the same.. and as soon as an 18th client connects to the server, performance starts to fail.   And note the performance degradation is not in an expected pattern... a going from 1 client to 17 clients the performance is roughly the same.. but going from 17 clients to 18 clients... the performance is 100x worse.. (this doens't make sense)

Furthermore, I designed another test, that would help me confirm that the performance issues are server related.  I designed the game so that if 1 single client has a poor connection or computer the whole game / server would not have performance issues for everyone else connected and playing on that server (of course the position and actions of that 1 laggy connection player would still be laggy ofc).   Here is how I set up this test.   I setup the remote server,  and then I had 3 different computers that would connect to this server, all from different internet connections. I'll call these A, B and C.  These 3 computers all connect to the server with 1 client each, and they are able to play around, game is working great, latency is low.   Then I have computer A connect 15 additional clients. At this time the latency for all players and the game starts to fail as explained before.  Even with computer B and C that are on separate connections with only 1 client each. The players  on computer B and C go to an entirely different part of the map from the clients from A... and B notices player C is laggy, and C notices player C is laggy.

This leads me to conclude that either.  Something is wrong with my sever / library so that 1 weak connection to the server makes all the other client connections slow as well, which shouldn't be the case.   Or alternatively, something is wrong with the server where as soon as their is a certain number of client connections the server performance tanks.  Eitherway something doesn't seem right.   All of these tests work fine on the same game with various websocket libraries.  So I am hoping, there is a way that this can be fixed,

**Comment by yandeu** [comment]
Does the increment or decrement of the frame rate affect the number of connections until it gets laggy? 

Can you try 15hz and 60hz?

Can you observe a message drop?
`channel.onDrop(drop => { })`

**Comment by sm64js** [comment]
A quick test,

yes at 15hz the number of connections until the server gets laggy is significantly higher.  I tested up to 25 players and it was still working fine.

I test with 1 computer that was running 23 connections, and that computer did get laggy and those players.   but the 2 other computers that only had 1 connection performed well, even with the total connections/players at 25.

So that is helpful, but would still want to understand why the server can't handle 30hz with 18 players.

**Comment by sm64js** [comment]
Can you clarify something?

I believe the docs said that the default behavior is to send messages as unreliable and unordered, correct? and I assume raw messages are no different?

then I am wondering since messages are not ordered, will the client automatically ignore older messages if it received a more recent message? Or do I need to implement that manually?

Thanks

**Comment by yandeu** [comment]
I think I know what is wrong, and I think I know why you do not have the same issue with websockets.

---

When the client updates its position (30 times per second), the server does: 

```js
// receive the update
channel.onRaw(bytes => { .. })`

// process the update
case 0: processPlayerData(channel.my_id, bytes.slice(1)); break

// call broadcastDataWithOpcode
broadcastDataWithOpcode(bytes, 0, allSockets[socketID].channel)

// broadcast the update
if (channel) channel.raw.broadcast.emit(newbytes)
```

`channel.raw.broadcast.emit` will be called 30/second/player. If you have 10 players connected, `channel.raw.broadcast.emit` will get called about 300 times per second. This does clearly overhead the WebRTC connection. 

I have read somewhere that some (or event most or all) WebSocket libraries queue their messages before sending. So with websockets the messages get queued and will be sent in batches. _I believe_.

WebRTC (geckos) is different. If you send 300 messages per seconds, the library will try to send 300 messages, which will not work. I recommend queuing the incoming client updates and send them all in batches, 30 (or more) times per seconds. 

---

A simple example of what I mean:
```js
let queue = []

const broadcastDataWithOpcode = (bytes, opcode, channel) => {
    if (bytes.length == undefined) bytes = Buffer.from(bytes)

    const newbytes = new Uint8Array(bytes.length + 1)
    newbytes.set([opcode], 0)
    newbytes.set(bytes, 1)

    // add to queue
    queue.push(newbytes)
}

// send all updates to all clients
setInterval(() => {
    geckos.raw.emit(queue)
    queue = []
}, 1000 / 30)

// every client will also get its own position, but you can simply filter them out on the client side.
```

**Comment by yandeu** [comment]
> unreliable and unordered, correct? and I assume raw messages are no different?

yes

> then I am wondering since messages are not ordered, will the client automatically ignore older messages if it received a more recent message? Or do I need to implement that manually?

You have to check it manually.

**Comment by sm64js** [comment]
Okay awesome! thank you @yandeu 

Interesting, I did not realize that websockets queue and batch their messages under the hood although that would make sense.

I do already have the game worked out to send all the messages in a list message, and send at fixed interval like you show... there are some complicated cases where this method is more difficult, that I won't get into, but that's fine, I can work it out.

I just wanted to make sure something isn't setup wrong, and it will perform optimally.  

So say, I do have all the messages send in a list and send at exactly 30hz... and say I have 100 players each message is 100 bytes.  so 300KB/s.   Do you think webRTC and this library will be able to support that?  It's challenging for me to test this, because I would need so many different computers and hands ha?  Have their been tests with 100 or more different client connections?

**Comment by yandeu** [comment]
> Interesting, I did not realize that websockets queue and batch their messages under the hood although that would make sense.

I'm not 100% sure about it.

> So say, I do have all the messages send in a list and send at exactly 30hz... and say I have 100 players each message is 100 bytes. so 300KB/s.

So every player receives 300KB/s and the server sends 30MB/s.

---

I will try to test it. I plan to setup a gecko.io server and connect 100 client from another server with puppeteer. Finally I will open the game in the browser and see if it works or not.

I will use a modified version of [phaser3-multiplayer-game-example](https://github.com/geckosio/phaser3-multiplayer-game-example) (just made a new benchmark branch https://github.com/geckosio/phaser3-multiplayer-game-example/commit/131547c39223fd4634a11b5cf90d95d99535a5fc), since it does already have a test script which opens some puppeteer connections.

Not sure if I will be able to make it this on a server this week.

**Comment by sm64js** [comment]
>So every player receives 300KB/s and the server sends 30MB/s.

Ah right! Yea got to keep in mind the server speed. but yea the server should have a good gigabit connection

>I will try to test it. I plan to setup a gecko.io server and connect 100 client from another server with puppeteer. Finally I will open the game in the browser and see if it works or not.

Oh thank you!! I greatly appreciate that.  puppeteer is a tool to emulate several clients connecting and acting like a real client would?

Yea let me know when you test it, and I'll continue development and testing with a slightly smaller amount of players/connections for now.

Let me know if you have updates, but I am content now and will close this issue.

**Comment by yandeu** [comment]
> puppeteer is a tool to emulate several clients connecting and acting like a real client would?

yes

> Let me know if you have updates

I tested it on some servers. I had no success connecting 100 clients with 100 bytes at 30fps each. It was too laggy :/
Did you successfully test that many connections with WebSockets?

**Comment by sm64js** [comment]
Well, I tested with about 30 clients with websockets and it worked pretty well.

I know games like agar.io work well with over 200 players using websockets.

And I understand compared to most non web browser games using traditional UDP, 300KB/s to each client is fairly small.

**Comment by sm64js** [comment]
>I tested it on some servers. I had no success connecting 100 clients with 100 bytes at 30fps each. It was too laggy :/

I am wondering what do you think is the bottleneck or limiting factor here?  server connection speed? client connection speed? server processing time? client processing?

So when I send the combined list of data from all players, whether there are 10 players or 100 players... I will apply compression to that message which may bring down size of data by 50% or a little more in what I have seen.  Additionally, I think my game will run alright if I send data at 15fps.  So hopefully these things might enable even more players
