### ISSUE TITLE
[HELP] How to host this in prod and open up ports correctly?

### ISSUE THREAD

**Issue by sm64js** [geckosio/geckos.io#50]
Hello,

I have geckos.io working  locally, and on my local network but, I have not figured out how to host it on a remote server, or allow remote connections in.

I decided to start with a simple hosting example, so I am trying to host the "simple-chat-example," and I setup a remote server with Ubuntu (via Digital Ocean), I could use a different distro if that is recommended though. I am not using docker or a load balancer or anything special here.

I am able to run the node server on the server, and am able to get the static webpage to load, but can't make the webRTC connection.  

I used ubuntu firewall commands (ufw) to allow connections though all ports 1-65535 on udp... the command was something like ```  sudo ufw allow 1:65535/udp``` and I also tried disabling ubuntu firewall all together.

In either case, I can host the server and connect and host the webpage, but can't establish webRTC connection.   (I am testing without SSL to be clear)

Some other things I am wondering, there is some talk of ICE servers? What are those? and also says in prod there is something about STUN and TURN servers, what are those and are those a requirement or just recommended?  What is the benefit of using those?

Thanks,
Any help would be greatly appreciated.

**Comment by yandeu** [comment]
There is a section called [Ice Servers](https://github.com/geckosio/geckos.io#ice-servers) in the README. It includes the code to add Ice Servers for testing and a nice video about WebRTC. You can't establish a WebRTC connection without STUN.

---

If you test the simple chat app example on the server, run `npm run production` instead of `npm start`.

It will use the default Ice Servers on line 7 in server.js
```js
iceServers: process.env.NODE_ENV === 'production' ? iceServers : []
```

**Comment by sm64js** [comment]
So I actually just was able to host and connect to  a geckos app on the remote server... both the chat example and my game is working.  (outside of ssl and load balancer for now).... but this is great! and progress.

But I am a little confused though, you mention this:
"You can't establish a WebRTC connection without STUN."

the remote server is working now, both when I put iceServers to the provided iceServers, and when I set iceServers to empty array.  so what is going on? When I set it to empty array that means it doesn't point to any stun server, however, I am still able to make a connection and play the game.. so how does that work?

then I am wondering, what is the downside of just using the default list of google stun servers that you provide? rather than setting up my own?

**Comment by sm64js** [comment]
I rambled a little bit here, but I am mostly wondering why when I was testing on a remote server, it was working even when I put iceServers to empty array.  If I simply continue in production with using an empty array for IceServers, would issues will I run into?
