### ISSUE TITLE
Geckos.io client side on Nodejs

### ISSUE THREAD

**Issue by Jack-2025** [geckosio/geckos.io#51]
I'm looking at how to connect a local script to the geckos.io server for data streaming.

I was wondering, is it possible to run the geckos.io client side code outside the browser, on Nodejs?  Or is there a recommended way of connecting to the geckos.io server maybe using another package on the client side?

Thanks!

**Comment by yandeu** [comment]
Geckos.io is only built for browser/server connections. You can't communicate between 2 geckos.io servers. But you can

**Comment by yandeu** [comment]
_sorry my phone froze and I accidentally clicked on close_

But you could connect 2 node servers using UDP (without geckos).

**Comment by Jack-2025** [comment]
I see

**Comment by yandeu** [comment]
@Jack-2025 There is now a way to connect 2 node servers. See https://github.com/geckosio/geckos.io/issues/64.
