### ISSUE TITLE
[HELP] geckos.io server behind NAT

### ISSUE THREAD

**Issue by yrucrem** [geckosio/geckos.io#55]
Hello!

First I wanted to say thanks for sharing this libray, that help reduce the entry barrier for working with WebRTC quite a lot.

I have a test setup to run the simple-chat-example where the server is behind NAT (more specifically on a virtual machine on a NAS). The ports are all forwarded properly (3478 and 5349 for TURN and I chose 7777 for the geckos.io server), but when I try to get a connection that does _not_ go over the local network it does not work.

After inspecting the responses to the `additional-candidates` endpoint contained only candidates local IP adresses (192.179.x.x). If I am not mistaken, this is where a TURN server would come in, so I setup coturn. But now I get _500 Internal Server Error_ responses from the `connections` endpoint.

If you could give me a hint whether this setup is flawed, and what I could do for the connections to work, it would be greatly appreciated. I saw the issue #53 which would also help me I think.

Thanks in advance for your input on this and best regards!
Patrick

**Comment by yandeu** [comment]
Have you added the STUN servers from google for testing?

```js
const geckos = require('@geckos.io/server').default
const { iceServers } = require('@geckos.io/server')
// or
import geckos, { iceServers } from '@geckos.io/server'

const io = geckos({ iceServers: iceServers })
```

**Comment by yrucrem** [comment]
Yes that is what I tried first, but responses from the `/additional-candidates` endpoint would only return candidates like 127.0.0.1 and 192.168.x.x, so when I loaded the client from something other than the local network, it could not connect to those IP addresses.

**Comment by yandeu** [comment]
Make sure the UDP ports from 1024 to 65535 are open publicly exposed.

**Comment by yrucrem** [comment]
Unfortunately this did not solve the issue.

I added some logging output for errors, and caught this exception when the data channel is created:

```
InvalidStateError: Failed to execute 'createDataChannel' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'.
    at RTCPeerConnection.createDataChannel (/home/yrucrem/tmp/geckos.io/packages/server/node_modules/wrtc/lib/peerconnection.js:234:37)
    at new ServerChannel (/home/yrucrem/tmp/geckos.io/packages/server/lib/geckos/channel.js:26:60)
    at new WebRTCConnection (/home/yrucrem/tmp/geckos.io/packages/server/lib/wrtc/webrtcConnection.js:112:25)
    at ConnectionsManagerServer.<anonymous> (/home/yrucrem/tmp/geckos.io/packages/server/lib/wrtc/connectionsManager.js:96:38)
    at step (/home/yrucrem/tmp/geckos.io/packages/server/lib/wrtc/connectionsManager.js:33:23)
    at Object.next (/home/yrucrem/tmp/geckos.io/packages/server/lib/wrtc/connectionsManager.js:14:53)
    at /home/yrucrem/tmp/geckos.io/packages/server/lib/wrtc/connectionsManager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/yrucrem/tmp/geckos.io/packages/server/lib/wrtc/connectionsManager.js:4:12)
    at ConnectionsManagerServer.createConnection (/home/yrucrem/tmp/geckos.io/packages/server/lib/wrtc/connectionsManager.js:66:16)
```

This only happens when I use my coturn server as `iceServers` (both are the same machine, but one time the local address, and one time the external one; both ports are correctly forwarded):
```
const io = geckos({
  iceServers: [
    { "urls": "turn:192.168.0.101:3478" },
    { "urls": "turn:external.ip.address:5349" }
  ]
})
```

My grasp of WebRTC is not firm enough yet, so I cannot really do something with that error message. I was hoping that you could point me in the right direction.

I really appreciate your feedback, thanks for your answers so far and also in advance for any further tipps.

**Comment by yandeu** [comment]
I'm not even sure if a turn server is needed (or if it even works). Normally if you server has a public IP and open UDP ports, every client should be able to connect. It is always the server that make the offer and looks for its external IP.

So in short:
- Forget about TURN
- Add STUN
- Make your server accessible via UDP 1024 - 65535

**Comment by yrucrem** [comment]
Thank you very much! You are perfectly right, TURN was the wrong direction here. Once I used coturn as a STUN server and configured the local/external IP matches correctly it worked.

I'm closing this issue. Thanks again!
