### ISSUE TITLE
[HELP] Concept and best practises of running a 3D engine server side (Babylon.js null engine)

### ISSUE THREAD

**Issue by panuchka** [geckosio/geckos.io#56]
[Babylon.js](https://www.babylonjs.com/games) is a webgl/webgpu engine that has many cool features. It also offers the '[null engine](https://doc.babylonjs.com/features/nullengine)' version, which can be used without browser. Therefore this engine could be used as an engine in an authoritative game server such as geckos.io.

I realize there is the example using geckos.io with [enable3d](https://github.com/geckosio/upd-vs-tcp-test), but it would be nice to have an example or conceptual base to create a base for a game (with physics if possible) with some other 3D engine as well. Babylon.js seems pretty good candidate, since it has many powerful features and the library seems mature enough.

So the actual things I'm asking for conceptual help and examples:

- Integrating Babylon.js null engine with geckos (with physics)
- General information of building an authoritative game with geckos, using Babylon.js null engine

**Comment by m0dE** [comment]
I also want to know if there's any example of geckos running with 3D physics (server authoratative)
