### ISSUE TITLE
(node:29928) UnhandledPromiseRejectionWarning: ReferenceError: RTCPeerConnection is not defined

### ISSUE THREAD

**Issue by OrlandoLuque** [geckosio/geckos.io#57]
Hellow!

Executing it from node, after installing geckos from npm, I got the next error:

> (node:29928) UnhandledPromiseRejectionWarning: ReferenceError: RTCPeerConnection is not defined
>     at PeerConnection.<anonymous> (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\wrtc\peerConnection.js:49:25)
>     at step (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\wrtc\peerConnection.js:33:23)
>     at Object.next (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\wrtc\peerConnection.js:14:53)
>     at C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\wrtc\peerConnection.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\wrtc\peerConnection.js:4:12)
>     at PeerConnection.connect (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\wrtc\peerConnection.js:44:16)
>     at ClientChannel.<anonymous> (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\geckos\channel.js:147:66)
>     at step (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\geckos\channel.js:33:23)
>     at Object.next (C:\dev\WebstormProjects\game1client\node_modules\@geckos.io\client\lib\geckos\channel.js:14:53)

I am using one of the examples you gave in the documentarion, adding the url so it does not fail:

> //import geckos from '@geckos.io/client'
> 
> const geckos = require('@geckos.io/client').default
> 
> 
> 
> // or add a minified version to your index.html file
> // https://github.com/geckosio/geckos.io/tree/master/bundles
> 
> const channel = geckos({ port: 3000, url: 'http://127.0.0.1' }) // default port is 9208
> 
> channel.onConnect(error => {
>     if (error) {
>         console.error(error.message)
>         return
>     }
> 
>     channel.on('chat message', data => {
>         console.log(`You got the message ${data}`)
>     })
> 
>     channel.emit('chat message', 'a short message sent to the server')
> })
>

**Comment by yandeu** [comment]
Have you tried the [chat app example](https://github.com/geckosio/simple-chat-app-example)? Does it work?

**Comment by OrlandoLuque** [comment]
Yep, it works!

![image](https://user-images.githubusercontent.com/11312932/96791210-51324c00-13f8-11eb-9045-d6a45e6f8759.png)

**Comment by OrlandoLuque** [comment]
ok, I got some time...

Copied your code to my node files and the same problem!
![image](https://user-images.githubusercontent.com/11312932/97086377-2f68dd00-1623-11eb-9e26-e3d2173482f3.png)

**Comment by yandeu** [comment]
Do you run `@geckos.io/client` on nodejs? It does not work on nodejs, only in the browser.

**Comment by OrlandoLuque** [comment]
oh!

No easy way to do it to work on node, right??

Thanks!

**Comment by yandeu** [comment]
No, there is no way to make it work on node. Only the package `@geckos.io/server` works on node.

**Comment by OrlandoLuque** [comment]
ok! thanks!

I am encapsulating it in html + electron now and it works :-)
