### ISSUE TITLE
Can I create a geckos client connection from nodeJS?

### ISSUE THREAD

**Issue by sm64js** [geckosio/geckos.io#64]
When I try to make a client connection in node using 
```
const geckos = require('@geckos.io/client').default
const new_channel = geckos({ url: "http://127.0.0.1", port: 9208 })
```

it fails with the error ReferenceError: RTCPeerConnection is not defined

and I assume this is because the client is normally ran in a webbrowser that relies on some built in browser functionality.

I want to make a nodejs geckos client that connects to geckes nodejs server.  There must be a way because I feel the server already has this functionality using node webrtc... and it just needs to be separated out from the signaling server?

Thanks

**Comment by sm64js** [comment]
I think you told me once you were doing this from puppeteer?  I just found that node package and tried using that... but don't think I have it setup quite right.

when I try making a geckos client connection I still get: `ReferenceError: RTCPeerConnection is not defined`

**Comment by snuffysasa** [comment]
Update, I figured this out with puppeteer.

**Comment by snuffysasa** [comment]
It would be nice if there was an easier way though

**Comment by yandeu** [comment]
There is another way. See the [stress-test](https://github.com/geckosio/stress-test) repo.

**Comment by rockey2020** [comment]
same question

Geckos.io signaling server is running on port 10086
file:///Users/rockey/WebstormProjects/darwin.node/node_modules/@geckos.io/client/lib/wrtc/peerConnection.js:5
        const webRTCPcSupported = RTCPeerConnection || webkitRTCPeerConnection; // eslint-disable-line no-undef
                                  ^

ReferenceError: RTCPeerConnection is not defined
    at PeerConnection.connect (file:///Users/rockey/WebstormProjects/darwin.node/node_modules/@geckos.io/client/lib/wrtc/peerConnection.js:5:35)
    at ClientChannel.onConnect (file:///Users/rockey/WebstormProjects/darwin.node/node_modules/@geckos.io/client/lib/geckos/channel.js:86:52)
    at startClient (file:///Users/rockey/WebstormProjects/darwin.node/apps/anynat/src/service/client/index.ts:4:13)
    at <anonymous>
    at async file:///Users/rockey/WebstormProjects/darwin.node/apps/anynat/src/index.ts:17:5
