### ISSUE TITLE
Unable to install in node 15.0.1 environment

### ISSUE THREAD

**Issue by 1cgonza** [geckosio/geckos.io#65]
Getting the following error when trying to install either client or server packages.

`error wrtc@0.4.6: The engine "node" is incompatible with this module. Expected version "^8.11.2 || ^10.0.0 || ^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0". Got "15.0.1"`

**Comment by yandeu** [comment]
Downgrade your node version to v14.

**Comment by ouya99** [comment]
@yandeu having same problem, could you maybe make it work for node 15.6 ?

https://github.com/node-webrtc/node-webrtc/issues/658

suggests that the webrtc issue has been solved. Some people unfortunately (M1 macbook) can only use node15 :(

**Comment by yandeu** [comment]
I just tried it on v15.6, but it failed.

**Comment by yandeu** [comment]
Looks like [version 2](https://github.com/geckosio/geckos.io/commits/v2) will work on node v15.

**Comment by yandeu** [comment]
You can now try version 2 (dev)

```console
 npm i @geckos.io/client@dev @geckos.io/server@dev
```

**Comment by ouya99** [comment]
@yandeu tried it, it fixes the node issue, but your new dependency node-datachannel is not compiling (they only have pre-compiled arm-libs for win, linux) on mac-arm64

After adding

set(OPENSSL_ROOT_DIR ${OPENSSL_ROOT_DIR} /opt/homebrew/opt/openssl@1.1/)
set(OPENSSL_CRYPTO_LIBRARY ${OPENSSL_ROOT_DIR}/lib/libcrypto.dylib CACHE FILEPATH "" FORCE)
set(OPENSSL_SSL_LIBRARY ${OPENSSL_ROOT_DIR}/lib/libssl.dylib CACHE FILEPATH "" FORCE)

to the CMakeLists (of the node-datachannel project) it compiles, so principally i can run v2 now , but would have to first compile node-datachannel, checkout geckos.io and adjust all paths to my own arm-64 lib.

Filed an issue https://github.com/murat-dogan/node-datachannel/issues/28 to simply installation via prebuilt

**Comment by ouya99** [comment]
see https://github.com/murat-dogan/node-datachannel/issues/28 
solved it by changing OPENSSL location

**Comment by panuchka** [comment]
I have a similar problem with version 2 on Windows 10 machine. Installation apparently requires cmake and visual studio, is this true?

**Comment by ouya99** [comment]
@panuchka yes it requires cmake. I am sure not if visual studio is required. I am on MacOS. But some c++ compiler should be installed. Check the build scripts of the dependencies to see what is required

**Comment by yandeu** [comment]
Sure it still needs cmake on Windows 10 with node v15?

Looks like prebuilds for v15 were [added today](https://github.com/murat-dogan/node-datachannel/commit/9352e4ffe51156b2a8f66fcb2a8e044dfd65e8f4).

I added the latest node-datachannel version to the [v2 branch](https://github.com/geckosio/geckos.io/tree/v2) and the build time reduced from 4m 56s to only 1m 39s, which is about the same time it always took for node v14 and v12

Anyways, I will publish `v2.0.0-dev.2` in one hour or so. @panuchka please wait for installing cmake and try `v2.0.0-dev.2` instead first.

**Comment by ouya99** [comment]
I do not see prebuilds following your link. 

on my machine (macOs) cmake is used to build it. But I am not 100% sure about Windows, Linux, but I did not find any prebuild files either, so I assume it uses cmake to build it locally, which murat also confirmed in my issue

**Comment by yandeu** [comment]
I believe @murat-dogan is saying that his [workflow](https://github.com/murat-dogan/node-datachannel/blob/master/.github/workflows/build.yml) does not generate and upload prebuilds for M1, since GitHub Actions do not support M1 yet. All other prebuilds are available. And since today also for Node.js v15.

On my Windows machine (Windows 10 with Node.js v14.15.3), `v2.0.0-dev.1` works even though CMake is not installed:
```console
ERR! OMG CMake is not installed. Install CMake.
```

**Comment by ouya99** [comment]
it generates prebuilds for M1, simply by generating prebuild for mac. My M1-system can handle this, cause node15 is an arm-version and the toolchain too. My only mistake was having the wrong path for OPENSSL, with that even your v2-1 runs without any issue simply by typing "npm i"

**Comment by yandeu** [comment]
@panuchka dev.2 is now on npm (`npm i @geckos.io/server@2.0.0-dev.2`).

---

> it generates prebuilds for M1, simply by generating prebuild for mac. My M1-system can handle this, cause node15 is an arm-version and the toolchain too. My only mistake was having the wrong path for OPENSSL, with that even your v2-1 runs without any issue simply by typing "npm i"

I see. Well, I have nearly never used mac so I know absolutely nothing about it.

**Comment by panuchka** [comment]
Yeap, `npm install` went through this time! Thank you @yandeu ! ❤️

**Comment by yandeu** [comment]
It seems, this issue can be closed?

Make sure you [join the discussions](https://github.com/geckosio/geckos.io/discussions).
