### ISSUE TITLE
Possibility to check connection origin/method

### ISSUE THREAD

**Issue by arthurb123** [geckosio/geckos.io#7]
Is it possible to check the "origin" or method of a connection on the server-side?

My problem is as follows: whenever a client connects to the server address via the browser I dynamically serve files. However clients can also connect through the client side by making a connection to the address the server is running on via script;
```geckos({ url: 'localhost', port: 1337 })```
This method of connecting could be considered indirect as it bypasses the need of getting files from the server and allows for offline file usage, which I do not want to  be possible.

To make a long story short, can I check when a connection gets made on the server-side if the client connected directly via the available address or by making a connection through script?
In Socket.IO this can be checked with the socket.handshake.xdomain boolean, but I know that the protocols are completely different so I'm not sure if this is possible in it's entirety with UDP.

Thanks in advance!

**Comment by yandeu** [comment]
Sorry for the late response.

I'm not familiar with socket.handshake.xdomain.

In short, you only want to allow users to connect to the server from a specific website?

I do not know if this is possible with webRTC, but since the signaling is done via http/https, you have access to the origin header and you can set the Access-Control-Allow-Origin.

```ts
// packages/server/src/httpServer
server.on('request', async (req: http.IncomingMessage, res: http.ServerResponse) => {
  console.log(req.headers.origin)

// packages/server/src/httpServer/setCors.ts
const SetCORS = (res: http.ServerResponse) => {
  res.setHeader('Access-Control-Allow-Origin', 'https://yourwebsite.com')
```
Is this what you are looking for? Should I implement some useful functions for this?

**Comment by arthurb123** [comment]
Thanks for the response, no problem for the delay :)
This would indeed fix the issue I am facing, I thought about it a bit too hard that I never considered such a solution.
Some functions that were to make this easier to use would be greatly appreciated, if it is not too much of a hassle of course!

**Comment by yandeu** [comment]
I made the necessary changes in the [cors branch](https://github.com/geckosio/geckos.io/commits/cors).

You can now add the origin as a string or function like so:

```ts
const io = geckos({
  cors: { origin: 'https://yourwebsite.com' }
})
```
```ts
const io = geckos({
  cors: {
    origin: req => {
      // do some work and return a string
      return 'https://yourwebsite.com'
    }
  }
})
```
What do you think?
