### ISSUE TITLE
Allow the client to be used in a nodejs instance

### ISSUE THREAD

**Issue by TroyKomodo** [geckosio/geckos.io#73]
https://github.com/geckosio/geckos.io/blob/0101a7a70a2fae8603ca1c8ea599d3214ab9e0d8/packages/client/src/wrtc/peerConnection.ts#L4

Perhaps, if window does not exist import `RTCPeerConnection` from node-webrtc?

**Comment by bil-ash** [comment]
Even I would like the same to be implemented [because](https://github.com/geckosio/geckos.io/discussions/90#discussioncomment-501387) . @yandeu any thoughts on this?

**Comment by yandeu** [comment]
It should be easy to add this in v2.

**Comment by jaburns** [comment]
Don't close it, github actions bot. I'm interested in this feature.

**Comment by KingCosmic** [comment]
also interested in this.

**Comment by Jalcantara88** [comment]
I too need a solution for this

**Comment by ChrisDiPiero** [comment]
Yes, please. I also need a solution.

**Comment by gutnar** [comment]
I managed to use the client in NodeJS by providing some global variables from `wrtc`, `node-fetch` and `ws` packages.

```ts
// Polyfills
import wrtc from "wrtc";
import fetch from "node-fetch";
import { WebSocket } from "ws";

global.RTCPeerConnection = wrtc.RTCPeerConnection;
global.RTCSessionDescription = wrtc.RTCSessionDescription;
// @ts-ignore
global.fetch = fetch;
// @ts-ignore
global.WebSocket = WebSocket;

// Client can now be used
import geckos from "@geckos.io/client";
```

**Comment by TroyKomodo** [comment]
I no longer need this. But @gutnar's solution should likely be PR'ed.

**Comment by Codezilluh** [comment]
Installing two additional packages that will only be used by a small fraction of people seems like a waste to me. Someone should just make a wrapper module for geckos, so those that need this functionality can install that instead.

**Comment by TroyKomodo** [comment]
I think, you are confused as to how the node bundle works. If you are using this for web browser I believe this doesn't make a difference

**Comment by Codezilluh** [comment]
It would add two extra (rather large) dependencies to the package.

**Comment by emansom** [comment]
> It would add two extra (rather large) dependencies to the package.

Which a tree shake algorithm, which most bundlers implement, would filter out.
