### ISSUE TITLE
Can't resolve 'http' in 'C:\...\node_modules\@geckos.io\server\lib\geckos'

### ISSUE THREAD

**Issue by 0ql** [geckosio/geckos.io#79]
Hello,

I am importing geckos in typescript with
`import geckos from '@geckos.io/server'`
the compiler then throws the Error:
`Can't resolve 'http' in 'C:\...\node_modules\@geckos.io\server\lib\geckos'`

Am I missing something?

Thanks in advance

**Comment by fviz** [comment]
I was having the same problem. In your webpack config, add

`resolve: {
        fallback: {
            "http": false
        }
    }`

This should make it load the library properly

**Comment by yandeu** [comment]
Can you share your `tsconfig.json`?

**Comment by 0ql** [comment]
tsconfig.json
`{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "lib": ["ES2015", "DOM", "ScriptHost"],
    "strict": true,
    "strictPropertyInitialization": false,
    "esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"noImplicitAny": false
	}
}
`

**Comment by yandeu** [comment]
Try to add `"skipLibCheck": true`

**Comment by 0ql** [comment]
Thanks for helping me but now I am getting the Error:
`webpack://..././node_modules/wrtc/lib/browser.js?:3
exports.MediaStream = window.MediaStream;
ReferenceError: window is not defined
`

**Comment by 0ql** [comment]
This is my `webpack.config.js`
```
const HtmlWebpackPlugin = require('html-webpack-plugin')
const path = require('path')

module.exports = {
  mode: 'development',
	entry: './src/client/client.ts',
  output: {
    path: path.resolve(__dirname, './dist/client'),
    filename: 'bundle.js',
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
  },
  module: {
    rules: [{ test: /\.tsx?$/, loader: 'ts-loader' }],
  },
	plugins: [new HtmlWebpackPlugin({ template: './src/client/index.html' })]
}

```

**Comment by yandeu** [comment]
The package `@geckos.io/server` does only work on the server-side. 
Please use the packages `@geckos.io/client` on the client instead.

**Comment by 0ql** [comment]
Sorry I send you the webpack config for the client side.

The client package is working fine.

This is the one for the server side:
```js
const path = require('path')

module.exports = {
  mode: 'development',
	entry: './src/server/server.ts',
  output: {
    path: path.resolve(__dirname, './dist/server'),
    filename: 'bundle.js',
  },
  resolve: {
		extensions: ['.ts', '.tsx', '.js']
  },
  module: {
    rules: [{ test: /\.tsx?$/, loader: 'ts-loader' }],
  }
}
```

**Comment by yandeu** [comment]
Try to exclude all `node_modules` from the bundle. Use the package [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals).

**Comment by 0ql** [comment]
It works now. Thanks for the help. Great lib btw
