### ISSUE TITLE
Channel close feature.

### ISSUE THREAD

**Issue by ohmed** [geckosio/geckos.io#8]
Hey. Was searching for client force `disconnect` [on the server side], but didn't noticed this feature anywhere in the code [only close calling when caught and error using try].
There's `.close()` for server in general and disconnects all clients at once. But no such method for only particular channel.
Or I'm missing something ?
If suggestion is ok can make a PR with this feature `channel.close()`.

**Comment by yandeu** [comment]
You're right. This is missing.

I just added this feature to a [new branch](https://github.com/geckosio/geckos.io/tree/close-single-channel). Can you test it?

**Comment by ohmed** [comment]
Will try it today evening! thx!

**Comment by yandeu** [comment]
You're welcome :)
Hope it works. Else, feel free to make a PR.
