### ISSUE TITLE
server.close() error in v2

### ISSUE THREAD

**Issue by yandeu** [geckosio/geckos.io#81]
server.close() crashes the program.
I have removed it from testing for now.

- https://github.com/geckosio/geckos.io/blob/v2/test/e2e/simple.test.js#L53
- https://github.com/geckosio/geckos.io/blob/v2/test/e2e/server.test.js#L78

**Comment by visgotti** [comment]
I spent a few hours.. and honestly I think I just broke shit more..

I'm pretty sure it's something to do in connectionManager.ts in the callback for - 

`pc.onStateChange(state => {})`

it winds up emitting a disconnect event before any other callback's from the http server.close.. I don't know why, but when the state param in the callback is `"disconnected"`, both `connection.state`, and _connection.channel.webrtcConnection.state_ are still `"open"`

I got the test to pass by writing the reason to a text file then reading it back in a setTimeout.. but I have no clue why it can't assert it in the callback.

Something is fucked lol good luck.

**Comment by yandeu** [comment]
@visgotti Thanks for your help!

> Something is fucked lol good luck.

🤣 Yes! I'm sure it will work someday :)

**Comment by visgotti** [comment]
Would you be opposed to switching the test framework? I feel like part of the issue may be jest running tests parallelly? It's at least making debugging a bit more difficult, there was definitely some weird timing issues going on when I was trying to log output in callbacks. I'm going to be implementing node dataChannel into my framework so if I figure anything else out i'll definitely come back to let you know

**Comment by yandeu** [comment]
> Would you be opposed to switching the test framework? I feel like part of the issue may be jest running tests parallelly? It's at least making debugging a bit more difficult

I never use Jest for debugging. I always make a dev package for debugging and developing an app. 

For debugging geckos.io, I made the package [chatApp](https://github.com/geckosio/geckos.io/tree/master/packages/chatApp).
If you download the geckos.io repo, `npm start` will automatically start the chatApp.

I only use Jest in a GitHub workflow to make sure nothing broke during the last commit.

I will also have another look at this issue in few days.

**Comment by yandeu** [comment]
It looks like it works now!

I didn't have to change the code.

I just update to `puppeteer@7` and `node-datachannel@0.0.24`. 

Also, I had to make sure the server closes after each test:
```js
afterAll(async () => {
  const close = () => {
    return new Promise(resolve => {
      server.close(() => {
        resolve()
      })
    })
  }

  await close()
})
````
