### ISSUE TITLE
No connection established in Docker environment

### ISSUE THREAD

**Issue by tsafs** [geckosio/geckos.io#99]
I can't get the `@geckos.io/client@dev` and  `@geckos.io/server@dev` working.

**Describe the bug**

The client does not seem to establish a connection with the server. I cannot tell where the connection is failing, because I get no error message at all. The callbacks `onConnection` on both client and server are just not called.

When I stop the server, the browser (Chrome) outputs the following, indicating that there was some sort of effort to establish a connection:

```
connectionsManager.ts:49 GET http://localhost:3001/.wrtc/v2/connections/SetnpSP9JK0wqWxsHzqBm4pH/additional-candidates net::ERR_EMPTY_RESPONSE
(anonymous) @ connectionsManager.ts:49
step @ index.ts:4
(anonymous) @ index.ts:4
(anonymous) @ index.ts:4
push../node_modules/@geckos.io/client/lib/wrtc/connectionsManager.js.__awaiter @ index.ts:4
ConnectionsManagerClient.fetchAdditionalCandidates @ connectionsManager.ts:48
(anonymous) @ connectionsManager.ts:142
setTimeout (async)
(anonymous) @ connectionsManager.ts:141
(anonymous) @ connectionsManager.ts:140
step @ index.ts:4
(anonymous) @ index.ts:4
fulfilled @ index.ts:4
Promise.then (async)
step @ index.ts:4
fulfilled @ index.ts:4
Promise.then (async)
step @ index.ts:4
(anonymous) @ index.ts:4
push../node_modules/@geckos.io/client/lib/wrtc/connectionsManager.js.__awaiter @ index.ts:4
ConnectionsManagerClient.connect @ connectionsManager.ts:64
(anonymous) @ peerConnection.ts:18
step @ connectionsManager.ts:198
(anonymous) @ connectionsManager.ts:198
(anonymous) @ connectionsManager.ts:198
push../node_modules/@geckos.io/client/lib/wrtc/peerConnection.js.__awaiter @ connectionsManager.ts:198
PeerConnection.connect @ peerConnection.ts:10
(anonymous) @ channel.ts:112
step @ vendors~main.chunk.js:138
(anonymous) @ vendors~main.chunk.js:69
(anonymous) @ vendors~main.chunk.js:41
push../node_modules/@geckos.io/client/lib/geckos/channel.js.__awaiter @ vendors~main.chunk.js:20
ClientChannel.onConnect @ channel.ts:109
(anonymous) @ index.js:7
./src/index.js @ index.js:13
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:13
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.ts:4 Uncaught (in promise) TypeError: Failed to fetch
```

I haven't verified the bug on my host system without docker, as I think that would have no change in effect.

**Reproduction**

I  created a docker setup for both the client and server, see my repository here: https://github.com/sebastianfast/geckos.io_bug_report

Instructions on running the setup is in the README.

The docker containers are running on a Windows 10 host.

The latest v1 releases `@geckos.io/client` and  `@geckos.io/server` are working. However, there are problems too. Sometimes the client establishes a connection and sometimes it shows the same response as described at all - not establishing a connection and not showing any error message.

**Question**

Is there anything I can do to enable some kind of verbose logging, as there is no error message or warning given at all?

Is there missing software that is to be installed as dependencies?

I would be happy to offer my help if it is needed.

**Comment by yandeu** [comment]
Make sure all the necessary ports are open.

In my experience docker takes a long time to open multiple ports so you have to restrict the UDP port range to your container and in the geckos.io configs.

---

The example below opens the port of your app (`3000`), the geckos signaling server (`9208`) and the ports `50000-50200 (udp)` for up to 200 WebRTC connections.

```bash
docker run -d -p 3000:3000 -p 9208:9208 -p 50000-50200:50000-50200/udp my-app
```
```js
// server.js
const io = geckos({
  portRange: {
    min: 50000,
    max: 50200
  }
})

**Comment by yandeu** [comment]
See the [Docker Example](https://github.com/geckosio/docker-example#readme).
